<!-- jQuery UI 1.11.4 -->
<script src="<?php echo $iniObj->UIPath; ?>/plugins/jquery-ui/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="<?php echo $iniObj->UIPath; ?>/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js" integrity="sha512-GffPMF3RvMeYyc1LWMHtK8EbPv0iNZ8/oTtHPx9/cc2ILxQ+u905qIwdpULaqDkyBKgOaB57QTMg7ztg8Jm2Og==" crossorigin=""></script>
<script src="https://unpkg.com/leaflet.markercluster@1.4.1/dist/leaflet.markercluster.js"></script>
<!-- ChartJS -->
<script src="<?php echo $iniObj->UIPath; ?>/plugins/chart.js/Chart.min.js"></script>
<!-- date-range-picker -->
<script src="<?php echo $iniObj->UIPath; ?>/plugins/daterangepicker/daterangepicker.js"></script>
<script src="<?php echo $iniObj->UIPath; ?>/plugins/inputmask/jquery.inputmask.min.js"></script>
<!-- Sparkline -->
<script src="<?php echo $iniObj->UIPath; ?>/plugins/sparklines/sparkline.js"></script>
<!-- JQVMap -->
<script src="<?php echo $iniObj->UIPath; ?>/plugins/jqvmap/jquery.vmap.min.js"></script>
<script src="<?php echo $iniObj->UIPath; ?>/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
<!-- jQuery Knob Chart -->
<script src="<?php echo $iniObj->UIPath; ?>/plugins/jquery-knob/jquery.knob.min.js"></script>
<!-- daterangepicker -->
<script src="<?php echo $iniObj->UIPath; ?>/plugins/moment/moment.min.js"></script>
<!-- Select2 -->
<script src="<?php echo $iniObj->UIPath; ?>/plugins/select2/js/select2.full.min.js"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="<?php echo $iniObj->UIPath; ?>/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
<!-- Summernote -->
<script src="<?php echo $iniObj->UIPath; ?>/plugins/summernote/summernote-bs4.min.js"></script>
<!-- overlayScrollbars -->
<script src="<?php echo $iniObj->UIPath; ?>/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
<!-- AdminLTE App -->
<script src="<?php echo $iniObj->UIPath; ?>/dist/js/adminlte.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="<?php echo $iniObj->UIPath; ?>/dist/js/demo.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="<?php echo $iniObj->UIPath; ?>/dist/js/pages/dashboard.js"></script>
<!-- SweetAlert2 -->
<script src="<?php echo $iniObj->UIPath; ?>/plugins/sweetalert2/sweetalert2.min.js"></script>
<!-- Toastr -->
<script src="<?php echo $iniObj->UIPath; ?>/plugins/toastr/toastr.min.js"></script>
<!-- DataTables  & Plugins -->
<script src="<?php echo $iniObj->UIPath; ?>/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="<?php echo $iniObj->UIPath; ?>/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
<script src="<?php echo $iniObj->UIPath; ?>/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
<script src="<?php echo $iniObj->UIPath; ?>/plugins/datatables-buttons/js/buttons.print.min.js"></script>
<script src="<?php echo $iniObj->UIPath; ?>/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
<script src="<?php echo $iniObj->UIPath; ?>/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<!-- Summernote -->
<script src="<?php echo $iniObj->UIPath; ?>/plugins/summernote/summernote-bs4.min.js"></script>
<!-- AdminLTE App -->
<!-- fullCalendar 2.2.5 -->
<!-- <script src="<?php echo $iniObj->UIPath; ?>/plugins/moment/moment.min.js"></script> -->
<script src="<?php echo $iniObj->UIPath; ?>/plugins/fullcalendar/main.js"></script>
<script src="<?php echo $iniObj->UIPath; ?>/plugins/fullcalendar/locales-all.js"></script>
<!-- bs-custom-file-input -->
<script src="<?php echo $iniObj->UIPath; ?>/plugins/bs-custom-file-input/bs-custom-file-input.min.js"></script>
<script>
    $(function() {
        bsCustomFileInput.init();
    });
</script>
<script>

    function onlytext(){
        
    }


</script>
<script>
    var RAW_EN_LOCALE = {
        code: '<?= $lang->trl('en') ?>',
        week: {
            dow: 0,
            doy: 4,
        },
        direction: 'ltr',
        buttonText: {
            prev: '<?= $lang->trl('prev') ?>',
            next: '<?= $lang->trl('next') ?>',
            prevYear: '<?= $lang->trl('prev year') ?>',
            nextYear: '<?= $lang->trl('next year') ?>',
            year: '<?= $lang->trl('year') ?>',
            today: '<?= $lang->trl('today') ?>',
            month: '<?= $lang->trl('month') ?>',
            week: '<?= $lang->Trl('week') ?>',
            day: '<?= $lang->trl('day') ?>',
            list: '<?= $lang->trl('list') ?>',
        },
        weekText: '<?= $lang->trl('W') ?>',
        allDayText: '<?= $lang->trl('all-day') ?>',
        moreLinkText: '<?= $lang->trl('more') ?>',
        noEventsText: '<?= $lang->trl('No events to display') ?>',
    };
</script>
<script>
    var Toast = Swal.mixin({
        toast: true,
        position: 'top-end',
        showConfirmButton: false,
        timer: 3000
    });
</script>
<script>

    $(document).ready(function() {
        /*var map = new ol.Map({
        target: 'map',
        layers: [
            new ol.layer.Tile({
                source: new ol.source.OSM()
            }),
            
        ],
        view: new ol.View({
            //center: ol.proj.fromLonLat([2.4283815, 6.3611938]),
            center: ol.proj.fromLonLat([2.4283815, 6.3611938]),
            zoom: 8,
            
        })
    });*/

           /* var villes = {
                "Paris": { "lat": 6.3611938, "lon": 2.4283815 },
            };*/

            var villes = <?php echo json_encode($data['gps']['data']);?>;
            var tableauMarqueurs = [];

            // On initialise la carte
            var carte = L.map('map').setView([6.3611938, 2.4283815], 10);
            
            // On charge les "tuiles"
            L.tileLayer('https://{s}.tile.openstreetmap.fr/osmfr/{z}/{x}/{y}.png', {
                // Il est toujours bien de laisser le lien vers la source des données
                attribution: 'données © <a href="//osm.org/copyright">OpenStreetMap</a>/ODbL - rendu <a href="//openstreetmap.fr">OSM France</a>',
                minZoom: 1,
                maxZoom: 20
            }).addTo(carte);

            var marqueurs = L.markerClusterGroup();

            // On personnalise le marqueur
            var icone = L.icon({
                iconUrl: "marcker.png",
                iconSize: [50, 50],
                iconAnchor: [25, 50],
                popupAnchor: [0, -50]
            })

            // On parcourt les différentes villes
            for(ville in villes){
                // On crée le marqueur et on lui attribue une popup
                var marqueur = L.marker([villes[ville].gps_lat, villes[ville].gps_lon], {icon: icone}); //.addTo(carte); Inutile lors de l'utilisation des clusters
                marqueur.bindPopup("<p>"+villes[ville].firstname+" "+villes[ville].lastname+"</p>");
                marqueurs.addLayer(marqueur); // On ajoute le marqueur au groupe

                // On ajoute le marqueur au tableau
                tableauMarqueurs.push(marqueur);
            }
            // On regroupe les marqueurs dans un groupe Leaflet
            var groupe = new L.featureGroup(tableauMarqueurs);

            // On adapte le zoom au groupe
            carte.fitBounds(groupe.getBounds().pad(0.5));

            carte.addLayer(marqueurs);

        $('#example2').DataTable({
            "paging": true,
            "lengthChange": false,
            "ordering": true,
            "info": true,
            "autoWidth": false,
            "responsive": true,
            "searching": true,
            "language": {
                paginate: {
                    previous: "<?= $lang->trl('Previous') ?>",
                    next: "<?= $lang->trl('Next') ?>"
                },
                "lengthMenu": "<?= $lang->trl('Display _MENU_ records per page') ?>",
                "zeroRecords": "<?= $lang->trl('Nothing found - sorry') ?>",
                "info": "<?= $lang->trl('Showing page _PAGE_ of _PAGES_') ?>",
                "infoEmpty": "<?= $lang->trl('No records available') ?>",
                "infoFiltered": "(<?= $lang->trl('filtered from _MAX_ total records') ?>)",
                "search": "<?= $lang->trl('Search') ?>"
            }
        });
    });
</script>
</main>
</body>

</html>