<?php

$cartUser = $sqlData->getcontactCart($_SESSION['customer']['contact_id']);
$cartdetail = $sqlData->getcartdetail($cartUser['data'][0]->cart_id);
//$lib->debug($cartdetail);
//exit;

?>

<body>

    <div class="top-header">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6 col-md-7 d-none-lg">
                    <ul class="top-header-contact-info">
                        <li><i class='bx bx-phone-call'></i> <a href="#"></a></li>
                        <li><i class='bx bx-envelope'></i> <a href="#"><span></span></a></li>
                    </ul>
                </div>
                <div class="col-lg-6 col-md-12">
                    <ul class="top-header-menu">
                        <li>
                        </li>
                        <!--<li>
                            <div class="dropdown currency-switcher d-inline-block">
                                <button class="dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <span>USD <i class="bx bx-chevron-down"></i></span>
                                </button>
                                <div class="dropdown-menu">
                                    <a href="#" class="dropdown-item">USD</a>
                                    <a href="#" class="dropdown-item">INR</a>
                                    <a href="#" class="dropdown-item">GBP</a>
                                </div>
                            </div>
                        </li>-->
                        <?php if ($_SESSION['customer']['authValidated']) { ?>
                            <li>
                                <!--<div class="dropdown">
                                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Mon compte
                                    </button>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                        <a href="/cart" id="" class="dropdown-item">Mon Panier</a>
                                        <a href="/dashboard" id="" class="dropdown-item">Tableau de Bord</a>
                                        <a href="" id="userlogout" class="dropdown-item">Se déconnecter</a>
                                    </div>
                                </div>-->
                                <div>
                                    <?php if ($_SESSION['customer']['img']) { ?>
                                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <img src="<?= $iniObj->imgProfilePath . $userinfo['data'][0]->img ?>" width="40" height="40" class="rounded-circle">
                                        </a>
                                    <?php } else { ?>
                                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <img src="<?= $iniObj->UIPath ?>/uploads/user.jpg" width="40" height="40" class="rounded-circle">
                                        </a>
                                    <?php } ?>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                        <a class="dropdown-item" href="/dashboard">Tableau de Bord</a>
                                        <a class="dropdown-item" href="/cart">Mon panier</a>
                                        <a class="dropdown-item" href="/customer/userprofile">Paramètre</a>
                                        <a class="dropdown-item" id="userlogout" href="/userlogout">Se déconnecter</a>
                                    </div>
                                </div>
                            </li>
                        <?php  } else { ?>
                            <li><a href="#" data-toggle="modal" data-target="#loginModal"> <span class="d-none-lg"> Se Connecter </span> <i class="bx bx-user d-lg-none fs-18"></i> </a></li>
                            <li><a href="#" data-toggle="modal" data-target="#registerModal"> <span class="d-none-lg"> S'inscrire </span> <i class="bx bx-user d-lg-none fs-18"></i> </a></li>
                        <?php } ?>
                    </ul>
                </div>
            </div>
        </div>
    </div>