<?php
$currentHour = date("YmdHis"); // Generate a random number to be added to url for customer logged in (to prevent browser to cache html data

?>


        
        <script src="<?= $iniObj->UIPath ?>/js/bootstrap.bundle.min.js"></script>
        <script src="<?= $iniObj->UIPath ?>/js/magnific-popup.min.js"></script>
        <script src="<?= $iniObj->UIPath ?>/js/owl.carousel.min.js"></script>
        <script src="<?= $iniObj->UIPath ?>/js/owl.carousel2.thumbs.min.js"></script>
        <script src="<?= $iniObj->UIPath ?>/js/meanmenu.min.js"></script>
        <script src="<?= $iniObj->UIPath ?>/js/nice-select.min.js"></script>
        <script src="<?= $iniObj->UIPath ?>/js/rangeSlider.min.js"></script>
        <script src="<?= $iniObj->UIPath ?>/js/wow.min.js"></script>
        <script src="<?= $iniObj->UIPath ?>/js/form-validator.min.js"></script>
        <script src="<?= $iniObj->UIPath ?>/js/contact-form-script.js"></script>
        <script src="<?= $iniObj->UIPath ?>/js/ajaxchimp.min.js"></script>
        <script src="<?= $iniObj->UIPath ?>/js/main.js"></script>
        <script src="<?= $iniObj->UIPath ?>/js/notify.js"></script>
    </body>

    <!-- Mirrored from medishop.takstok.com/cart.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 13 Apr 2021 08:48:48 GMT -->
</html>