<?php
$currentHour = date("YmdHis"); // Generate a random number to be added to url for customer logged in (to prevent browser to cache html data
?>



<!-- jQuery  -->
<script src="<?= $iniObj->UIPath ?>/backoffice/js/jquery.min.js"></script>
<script src="<?= $iniObj->UIPath ?>/backoffice/js/bootstrap.bundle.min.js"></script>
<script src="<?= $iniObj->UIPath ?>/backoffice/js/metismenu.min.js"></script>
<script src="<?= $iniObj->UIPath ?>/backoffice/js/waves.js"></script>
<script src="<?= $iniObj->UIPath ?>/backoffice/js/simplebar.min.js"></script>
<script src="<?= $iniObj->UIPath ?>/backoffice/js/cropper.js"></script>

<!-- third party js -->
<script src="<?= $iniObj->UIPath ?>/backoffice/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="<?= $iniObj->UIPath ?>/backoffice/plugins/datatables/dataTables.bootstrap4.js"></script>
<script src="<?= $iniObj->UIPath ?>/backoffice/plugins/datatables/dataTables.responsive.min.js"></script>
<script src="<?= $iniObj->UIPath ?>/backoffice/plugins/datatables/responsive.bootstrap4.min.js"></script>
<script src="<?= $iniObj->UIPath ?>/backoffice/plugins/datatables/dataTables.buttons.min.js"></script>
<script src="<?= $iniObj->UIPath ?>/backoffice/plugins/datatables/buttons.bootstrap4.min.js"></script>
<script src="<?= $iniObj->UIPath ?>/backoffice/plugins/datatables/buttons.html5.min.js"></script>
<script src="<?= $iniObj->UIPath ?>/backoffice/plugins/datatables/buttons.flash.min.js"></script>
<script src="<?= $iniObj->UIPath ?>/backoffice/plugins/datatables/buttons.print.min.js"></script>
<script src="<?= $iniObj->UIPath ?>/backoffice/plugins/datatables/dataTables.keyTable.min.js"></script>
<script src="<?= $iniObj->UIPath ?>/backoffice/plugins/datatables/dataTables.select.min.js"></script>
<script src="<?= $iniObj->UIPath ?>/backoffice/plugins/datatables/pdfmake.min.js"></script>
<script src="<?= $iniObj->UIPath ?>/backoffice/plugins/datatables/vfs_fonts.js"></script>
<!-- third party js ends -->

<!-- Plugins js -->
<script src="<?= $iniObj->UIPath ?>/backoffice/plugins/autonumeric/autoNumeric-min.js"></script>
<script src="<?= $iniObj->UIPath ?>/backoffice/plugins/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
<script src="<?= $iniObj->UIPath ?>/backoffice/plugins/bootstrap-maxlength/bootstrap-maxlength.min.js"></script>
<script src="<?= $iniObj->UIPath ?>/backoffice/plugins/moment/moment.js"></script>
<script src="<?= $iniObj->UIPath ?>/backoffice/plugins/daterangepicker/daterangepicker.js"></script>
<script src="<?= $iniObj->UIPath ?>/backoffice/plugins/select2/select2.min.js"></script>
<script src="<?= $iniObj->UIPath ?>/backoffice/plugins/switchery/switchery.min.js"></script>
<script src="<?= $iniObj->UIPath ?>/backoffice/plugins/bootstrap-colorpicker/bootstrap-colorpicker.min.js"></script>
<script src="<?= $iniObj->UIPath ?>/backoffice/plugins/bootstrap-touchspin/jquery.bootstrap-touchspin.min.js"></script>
<script src="<?= $iniObj->UIPath ?>/backoffice/plugins/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
<script src="<?= $iniObj->UIPath ?>/backoffice/plugins/ckeditor/ckeditor.js"></script>

<!-- Init js-->
<script src="<?= $iniObj->UIPath ?>/backoffice/pages/advanced-plugins-demo.js"></script>

<!-- Datatables init -->
<script src="<?= $iniObj->UIPath ?>/backoffice/pages/datatables-demo.js"></script>



<!--dropify-->
<script src="<?= $iniObj->UIPath ?>/backoffice/plugins/dropify/dropify.min.js"></script>

<!--toastr-->
<script src="<?= $iniObj->UIPath ?>/backoffice/toastr/build/toastr.min.js"></script>

<!-- Init js-->
<script src="<?= $iniObj->UIPath ?>/backoffice/pages/fileuploads-demo.js"></script>

<!-- App js -->
<script src="<?= $iniObj->UIPath ?>/backoffice/js/theme.js"></script>


<script src="<?= $iniObj->UIPath ?>/js/notify.js"></script>

</body>


<!-- Mirrored from myrathemes.com/lunoz/layouts/vertical/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 16 Apr 2021 16:52:40 GMT -->

</html>