<?php

if ($iniObj->debugViews)
    echo __FILE__;
//$carouselActive = true;
$title = "Contact || ".$iniObj->serviceName;
include _VIEW_PATH . "/customer_common_header.phtml";
?>

<?php
include _VIEW_PATH . "/customer_common_top_bar.phtml";
?>

<?php
include _VIEW_PATH . $lib->lang . "/customer_menu.phtml";
?>

<section class="page-title-area">
    <div class="container">
        <div class="page-title-content">
            <h1>Contact</h1>
            <!-- <ul>
                <li><a href="index.html">Home</a></li>
                <li>Contact Us</li>
            </ul> -->
        </div>
    </div>
</section>


<section class="contact-area ptb-70">
    <div class="container">
        <div class="row align-items-center">
            <!-- <div class="col-lg-6 col-md-12">
                <div class="contact-form">
                    <h2>Get In Touch</h2>
                    <form id="contactForm">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="form-group">
                                    <label>Full Name</label>
                                    <input type="text" name="name" class="form-control" id="name" required data-error="Please enter your name">
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="form-group">
                                    <label>Email Address</label>
                                    <input type="email" name="email" class="form-control" id="email" required data-error="Please enter your email">
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="form-group">
                                    <label>Mobile No.</label>
                                    <input type="text" name="phone_number" class="form-control" id="phone_number" required data-error="Please enter your phone number">
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="form-group">
                                    <label>Subject</label>
                                    <input type="text" name="subject" class="form-control" id="subject">
                                </div>
                            </div>
                            <div class="col-lg-12 col-md-12 col-sm-12">
                                <div class="form-group">
                                    <label>Message</label>
                                    <textarea name="message" id="message" class="form-control" cols="30" rows="6" required data-error="Please enter your message"></textarea>
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>
                            <div class="col-lg-12 col-md-12 col-sm-12">
                                <button type="submit" id="submit-message" class="default-btn">Send Message</button>
                                <div id="msgSubmit" class="h3 text-center hidden"></div>
                                <div class="clearfix"></div>
                                <p id="msg" class="message"></p>
                            </div>
                        </div>
                    </form>
                </div>
            </div> -->
            <div class="col-lg-12 col-md-12">
                <div class="row">
                    <div class="col-lg-3 col-sm-6 col-md-6">
                        <div class="single-contact-info-box">
                            <div class="icon">
                                <i class="flaticon-placeholder"></i>
                            </div>
                            <h3>Adresse</h3>
                            <p><a href="#" target="#">3286 Still Pastures Drive Chester, SC 29706</a></p>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6 col-md-6">
                        <div class="single-contact-info-box">
                            <div class="icon">
                                <i class="flaticon-phone-ringing"></i>
                            </div>
                            <h3>Téléphone</h3>
                            <p><a href="#">Hotline: 16798</a></p>
                            <p><a href="#">Tech support: (+123) 555-0179</a></p>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6 col-md-6">
                        <div class="single-contact-info-box">
                            <div class="icon">
                                <i class="flaticon-email"></i>
                            </div>
                            <h3>Email</h3>
                            <p><a href="#"><span>yourname@email.com</span></a></p>
                            <p><a href="#">Skype: hello.theme</a></p>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6 col-md-6">
                        <div class="single-contact-info-box">
                            <div class="icon">
                                <i class="flaticon-clock"></i>
                            </div>
                            <h3>Heure d'Ouverture</h3>
                            <p>Lundi - Vendredi</p>
                            <p>8:00AM - 8:00PM</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<?php include _VIEW_PATH . $lib->lang . "/customer_common_footer.phtml"; ?>
<?php include _VIEW_PATH . "/customer_common_include_files.phtml"; ?>