<?php if ($iniObj->debugViews) echo __FILE__; ?>

<section class="facility-area bg-main-color pt-70 pb-40">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-sm-6 col-md-3 col-6">
                <div class="single-facility-box">
                    <div class="icon">
                        <i class="flaticon-free-shipping"></i>
                    </div>
                    <h3>Livraison Rapide</h3>
                    <p>Partout sur le Globe</p>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6 col-md-3 col-6">
                <div class="single-facility-box">
                    <div class="icon">
                        <i class="flaticon-headset"></i>
                    </div>
                    <h3>Support 24h/24 7j/7</h3>
                    <p>Contacter nous a n'importe quel moment</p>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6 col-md-3 col-6">
                <div class="single-facility-box">
                    <div class="icon">
                        <i class="flaticon-secure-payment"></i>
                    </div>
                    <h3>Paiement Sécurisé</h3>
                    <p>Votre paiement est bien protégé</p>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6 col-md-3 col-6">
                <div class="single-facility-box">
                    <div class="icon">
                        <i class="flaticon-return-box"></i>
                    </div>
                    <h3>Retour de d'Article</h3>
                    <p>Simple Politique de Retour</p>
                </div>
            </div>
        </div>
    </div>
</section>


<footer class="footer-area">
    <div class="container">
        <div class="footer-bar d-lg-none">
            <ul class="h-100 d-flex align-items-center justify-content-between pl-0">
                <li><a href="<?= $iniObj->siteUrl ?>"> <i class="bx bx-home-alt"></i> <span class="title">Acceuil</span></a></li>
                <li><a href="/shop"> <i class="bx bx-cart"></i> <span class="title">Boutique</span></a>
                </li>
                <li><a href="/cart"> <i class="bx bx-basket"></i> <span class="title">Panier</span></a></li>
                <li><a href="wishlist.html"> <i class="bx bx-heart"></i> <span class="title">Wishlist</span><span class="count">0</span></a></li>
            </ul>
        </div>
        <div class="row d-none-lg">
            <div class="col-lg-3 col-sm-6 col-md-6">
                <div class="single-footer-widget">
                    <a href="index.html" class="logo d-inline-block"><img src="<?= $iniObj->UIPath ?>/img/logo2.png" alt="image"></a>
                    <ul class="footer-contact-info">
                        <!-- <li><span>Hotline:</span> <a href="#">16768</a></li> -->
                        <li><span>Téléphone:</span> <a href="#">(+123) 555-0179</a></li>
                        <li><span>Email:</span> <a href="#"><span>yourname@email.com</span></a></li>
                        <li><span>Adresse:</span> <a href="#" target="#">645 Southern Street, California, USA</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6 col-md-6">
                <div class="single-footer-widget">
                    <h3>Information</h3>
                    <ul class="link-list">
                        <!-- <li><a href="javascript:void(0)">Strudture Chimique</a></li>
                        <li><a href="javascript:void(0)">Demande de Certificats</a></li>
                        <li><a href="javascript:void(0)">Fiche de sécurité</a></li> -->
                        <li><a href="/traking">Suivi de commande</a></li>
                        <li><a href="/contact">Contact</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6 col-md-6">
                <div class="single-footer-widget">
                    <h3>Customer Care</h3>
                    <ul class="link-list">
                        <li><a href="javascript:void(0)">FAQ</a></li>
                        <li><a href="/cart">Mon Panier</a></li>
                        <?php if($_SESSION['customer']['authValidated']): ?>
                        <li><a href="/customer/userprofile">Mon Compte</a></li>
                        <?php endif ; ?>
                        <!-- <li><a href="index.html">Newsletter</a></li> -->
                        <!-- <li><a href="terms-conditions.html">Purchasing Policy</a></li> -->
                    </ul>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6 col-md-6">
                <div class="single-footer-widget">
                    <h3>Nous acceptons les payements via</h3>
                    <ul class="payment-methods d-flex align-items-center">
                        <li><a href="javascript:void(0)" target="#"><img src="<?= $iniObj->UIPath ?>/img/payment-types/visa.png" alt="image"></a>
                        </li>
                        <li><a href="#" target="#"><img src="<?= $iniObj->UIPath ?>/img/payment-types/mastercard.png" alt="image"></a></li>
                        <li><a href="#" target="#"><img src="<?= $iniObj->UIPath ?>/img/payment-types/paypal.png" alt="image"></a>
                        </li>
                        <!-- <li><a href="#" target="#"><img src="<?= $iniObj->UIPath ?>/img/payment-types/descpver.png" alt="image"></a>
                        </li>
                        <li><a href="#" target="#"><img src="<?= $iniObj->UIPath ?>/img/payment-types/american-express.png" alt="image"></a></li> -->
                    </ul>
                    <h3>Suiver nous sur :</h3>
                    <ul class="social">
                        <li><a href="#" target="#"><i class='bx bxl-facebook-square'></i></a></li>
                        <li><a href="#" target="#"><i class="bx bxl-twitter"></i></a></li>
                        <li><a href="#" target="#"><i class='bx bxl-instagram-alt'></i></a></li>
                        <li><a href="#" target="#"><i class='bx bxl-linkedin-square'></i></a></li>
                        <li><a href="#" target="#"><i class='bx bxl-pinterest'></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom-area d-none-lg">
        <div class="container">
            <p>Copyright <i class='bx bx-copyright'></i>2021 Designed By <a href="javasript:void(0)" target="_blank">JIS Computing</a></p>
        </div>
    </div>
</footer>


<div class="modal fade loginModal" id="loginModal" tabindex="-1" aria-modal="true" role="dialog">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title">Connexion</h2>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><i class="bx bx-x"></i></button>
            </div>
            <div class="text-danger" id="error_msg"></div>
            <div class="text-success" id="success_msg"></div>
            <div class="modal-body">
                <form id="userlogin">
                    <div class="form-group">
                        <input type="text" id="email" name="email" class="form-control" placeholder="Email">
                    </div>
                    <div class="input-group form-group">
                        <input type="password" id="password" name="password" class="form-control" placeholder="Mot de passe">
                        <div class="input-group-prepend">
                           <div class="input-group-text"> <a href="javascript:void(0)" onclick="viewLoginPass()"><i class="fa fa-eye" aria-hidden="true"></i></a></div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="d-flex align-items-center justify-content-between">
                            <div class="form-check">
                                <input type="checkbox" class="form-check-input" id="remember-me">
                                <label class="form-check-label" for="remember-me">Se souvenir de moi</label>
                            </div>
                            <a href="/forgetpassword">Mot de passe oublié?</a>
                        </div>
                    </div>
                    <button type="submit" class="default-btn">Se connecter</button>
                </form>
                <span class="dont-account">Vous n'avez pas de compte? <a href="#" data-toggle="modal" data-target="#registerModal">Créer un compte!</a></span>
            </div>
        </div>
    </div>
</div>


<div class="modal fade registerModal" id="registerModal" tabindex="-1" aria-modal="true" role="dialog">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title">S'inscrire</h2>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><i class="bx bx-x"></i></button>
            </div>
            <div class="text-danger">
                <p id="error_message"></p>
            </div>
            <div class="success">
                <p id="success_message"></p>
            </div>
            <div class="modal-body">
                <form method="POST" id="addUser" action="">
                    <div class="form-group">
                        <label for="lastname">Nom</label>
                        <input type="text" name="newlastname" id="newlastname" class="form-control" placeholder="Entrer votre nom">
                    </div>
                    <div class="form-group">
                        <label for="fistrname">Prénoms</label>
                        <input type="text" name="newfirstname" id="newfirstname" class="form-control" placeholder="Entrer votre prénom">
                    </div>
                    <div class="form-group">
                        <label for="address">Téléphone</label>
                        <input type="tel" name="newphone" id="newphone" class="form-control" placeholder="+33...">
                    </div>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="email" name="newemail" id="newemail" class="form-control" placeholder="Entrer votre email">
                    </div>
                    <!-- <div class="col-12">
                        <div class="form-group">
                            <label for="country">Pays de résidence</label>
                            <select id="country" name="country" class="fomr-select">
                                <option value="Afganistan">Afghanistan</option>
                                <option value="Albania">Albania</option>
                                <option value="Algeria">Algeria</option>
                                <option value="American Samoa">American Samoa</option>
                                <option value="Andorra">Andorra</option>
                                <option value="Angola">Angola</option>
                                <option value="Anguilla">Anguilla</option>
                                <option value="Antigua & Barbuda">Antigua & Barbuda</option>
                                <option value="Argentina">Argentina</option>
                                <option value="Armenia">Armenia</option>
                                <option value="Aruba">Aruba</option>
                                <option value="Australia">Australia</option>
                                <option value="Austria">Austria</option>
                                <option value="Azerbaijan">Azerbaijan</option>
                                <option value="Bahamas">Bahamas</option>
                                <option value="Bahrain">Bahrain</option>
                                <option value="Bangladesh">Bangladesh</option>
                                <option value="Barbados">Barbados</option>
                                <option value="Belarus">Belarus</option>
                                <option value="Belgium">Belgium</option>
                                <option value="Belize">Belize</option>
                                <option value="Benin">Benin</option>
                                <option value="Bermuda">Bermuda</option>
                                <option value="Bhutan">Bhutan</option>
                                <option value="Bolivia">Bolivia</option>
                                <option value="Bonaire">Bonaire</option>
                                <option value="Bosnia & Herzegovina">Bosnia & Herzegovina</option>
                                <option value="Botswana">Botswana</option>
                                <option value="Brazil">Brazil</option>
                                <option value="British Indian Ocean Ter">British Indian Ocean Ter</option>
                                <option value="Brunei">Brunei</option>
                                <option value="Bulgaria">Bulgaria</option>
                                <option value="Burkina Faso">Burkina Faso</option>
                                <option value="Burundi">Burundi</option>
                                <option value="Cambodia">Cambodia</option>
                                <option value="Cameroon">Cameroon</option>
                                <option value="Canada">Canada</option>
                                <option value="Canary Islands">Canary Islands</option>
                                <option value="Cape Verde">Cape Verde</option>
                                <option value="Cayman Islands">Cayman Islands</option>
                                <option value="Central African Republic">Central African Republic</option>
                                <option value="Chad">Chad</option>
                                <option value="Channel Islands">Channel Islands</option>
                                <option value="Chile">Chile</option>
                                <option value="China">China</option>
                                <option value="Christmas Island">Christmas Island</option>
                                <option value="Cocos Island">Cocos Island</option>
                                <option value="Colombia">Colombia</option>
                                <option value="Comoros">Comoros</option>
                                <option value="Congo">Congo</option>
                                <option value="Cook Islands">Cook Islands</option>
                                <option value="Costa Rica">Costa Rica</option>
                                <option value="Cote DIvoire">Cote DIvoire</option>
                                <option value="Croatia">Croatia</option>
                                <option value="Cuba">Cuba</option>
                                <option value="Curaco">Curacao</option>
                                <option value="Cyprus">Cyprus</option>
                                <option value="Czech Republic">Czech Republic</option>
                                <option value="Denmark">Denmark</option>
                                <option value="Djibouti">Djibouti</option>
                                <option value="Dominica">Dominica</option>
                                <option value="Dominican Republic">Dominican Republic</option>
                                <option value="East Timor">East Timor</option>
                                <option value="Ecuador">Ecuador</option>
                                <option value="Egypt">Egypt</option>
                                <option value="El Salvador">El Salvador</option>
                                <option value="Equatorial Guinea">Equatorial Guinea</option>
                                <option value="Eritrea">Eritrea</option>
                                <option value="Estonia">Estonia</option>
                                <option value="Ethiopia">Ethiopia</option>
                                <option value="Falkland Islands">Falkland Islands</option>
                                <option value="Faroe Islands">Faroe Islands</option>
                                <option value="Fiji">Fiji</option>
                                <option value="Finland">Finland</option>
                                <option value="France">France</option>
                                <option value="French Guiana">French Guiana</option>
                                <option value="French Polynesia">French Polynesia</option>
                                <option value="French Southern Ter">French Southern Ter</option>
                                <option value="Gabon">Gabon</option>
                                <option value="Gambia">Gambia</option>
                                <option value="Georgia">Georgia</option>
                                <option value="Germany">Germany</option>
                                <option value="Ghana">Ghana</option>
                                <option value="Gibraltar">Gibraltar</option>
                                <option value="Great Britain">Great Britain</option>
                                <option value="Greece">Greece</option>
                                <option value="Greenland">Greenland</option>
                                <option value="Grenada">Grenada</option>
                                <option value="Guadeloupe">Guadeloupe</option>
                                <option value="Guam">Guam</option>
                                <option value="Guatemala">Guatemala</option>
                                <option value="Guinea">Guinea</option>
                                <option value="Guyana">Guyana</option>
                                <option value="Haiti">Haiti</option>
                                <option value="Hawaii">Hawaii</option>
                                <option value="Honduras">Honduras</option>
                                <option value="Hong Kong">Hong Kong</option>
                                <option value="Hungary">Hungary</option>
                                <option value="Iceland">Iceland</option>
                                <option value="Indonesia">Indonesia</option>
                                <option value="India">India</option>
                                <option value="Iran">Iran</option>
                                <option value="Iraq">Iraq</option>
                                <option value="Ireland">Ireland</option>
                                <option value="Isle of Man">Isle of Man</option>
                                <option value="Israel">Israel</option>
                                <option value="Italy">Italy</option>
                                <option value="Jamaica">Jamaica</option>
                                <option value="Japan">Japan</option>
                                <option value="Jordan">Jordan</option>
                                <option value="Kazakhstan">Kazakhstan</option>
                                <option value="Kenya">Kenya</option>
                                <option value="Kiribati">Kiribati</option>
                                <option value="Korea North">Korea North</option>
                                <option value="Korea Sout">Korea South</option>
                                <option value="Kuwait">Kuwait</option>
                                <option value="Kyrgyzstan">Kyrgyzstan</option>
                                <option value="Laos">Laos</option>
                                <option value="Latvia">Latvia</option>
                                <option value="Lebanon">Lebanon</option>
                                <option value="Lesotho">Lesotho</option>
                                <option value="Liberia">Liberia</option>
                                <option value="Libya">Libya</option>
                                <option value="Liechtenstein">Liechtenstein</option>
                                <option value="Lithuania">Lithuania</option>
                                <option value="Luxembourg">Luxembourg</option>
                                <option value="Macau">Macau</option>
                                <option value="Macedonia">Macedonia</option>
                                <option value="Madagascar">Madagascar</option>
                                <option value="Malaysia">Malaysia</option>
                                <option value="Malawi">Malawi</option>
                                <option value="Maldives">Maldives</option>
                                <option value="Mali">Mali</option>
                                <option value="Malta">Malta</option>
                                <option value="Marshall Islands">Marshall Islands</option>
                                <option value="Martinique">Martinique</option>
                                <option value="Mauritania">Mauritania</option>
                                <option value="Mauritius">Mauritius</option>
                                <option value="Mayotte">Mayotte</option>
                                <option value="Mexico">Mexico</option>
                                <option value="Midway Islands">Midway Islands</option>
                                <option value="Moldova">Moldova</option>
                                <option value="Monaco">Monaco</option>
                                <option value="Mongolia">Mongolia</option>
                                <option value="Montserrat">Montserrat</option>
                                <option value="Morocco">Morocco</option>
                                <option value="Mozambique">Mozambique</option>
                                <option value="Myanmar">Myanmar</option>
                                <option value="Nambia">Nambia</option>
                                <option value="Nauru">Nauru</option>
                                <option value="Nepal">Nepal</option>
                                <option value="Netherland Antilles">Netherland Antilles</option>
                                <option value="Netherlands">Netherlands (Holland, Europe)</option>
                                <option value="Nevis">Nevis</option>
                                <option value="New Caledonia">New Caledonia</option>
                                <option value="New Zealand">New Zealand</option>
                                <option value="Nicaragua">Nicaragua</option>
                                <option value="Niger">Niger</option>
                                <option value="Nigeria">Nigeria</option>
                                <option value="Niue">Niue</option>
                                <option value="Norfolk Island">Norfolk Island</option>
                                <option value="Norway">Norway</option>
                                <option value="Oman">Oman</option>
                                <option value="Pakistan">Pakistan</option>
                                <option value="Palau Island">Palau Island</option>
                                <option value="Palestine">Palestine</option>
                                <option value="Panama">Panama</option>
                                <option value="Papua New Guinea">Papua New Guinea</option>
                                <option value="Paraguay">Paraguay</option>
                                <option value="Peru">Peru</option>
                                <option value="Phillipines">Philippines</option>
                                <option value="Pitcairn Island">Pitcairn Island</option>
                                <option value="Poland">Poland</option>
                                <option value="Portugal">Portugal</option>
                                <option value="Puerto Rico">Puerto Rico</option>
                                <option value="Qatar">Qatar</option>
                                <option value="Republic of Montenegro">Republic of Montenegro</option>
                                <option value="Republic of Serbia">Republic of Serbia</option>
                                <option value="Reunion">Reunion</option>
                                <option value="Romania">Romania</option>
                                <option value="Russia">Russia</option>
                                <option value="Rwanda">Rwanda</option>
                                <option value="St Barthelemy">St Barthelemy</option>
                                <option value="St Eustatius">St Eustatius</option>
                                <option value="St Helena">St Helena</option>
                                <option value="St Kitts-Nevis">St Kitts-Nevis</option>
                                <option value="St Lucia">St Lucia</option>
                                <option value="St Maarten">St Maarten</option>
                                <option value="St Pierre & Miquelon">St Pierre & Miquelon</option>
                                <option value="St Vincent & Grenadines">St Vincent & Grenadines</option>
                                <option value="Saipan">Saipan</option>
                                <option value="Samoa">Samoa</option>
                                <option value="Samoa American">Samoa American</option>
                                <option value="San Marino">San Marino</option>
                                <option value="Sao Tome & Principe">Sao Tome & Principe</option>
                                <option value="Saudi Arabia">Saudi Arabia</option>
                                <option value="Senegal">Senegal</option>
                                <option value="Seychelles">Seychelles</option>
                                <option value="Sierra Leone">Sierra Leone</option>
                                <option value="Singapore">Singapore</option>
                                <option value="Slovakia">Slovakia</option>
                                <option value="Slovenia">Slovenia</option>
                                <option value="Solomon Islands">Solomon Islands</option>
                                <option value="Somalia">Somalia</option>
                                <option value="South Africa">South Africa</option>
                                <option value="Spain">Spain</option>
                                <option value="Sri Lanka">Sri Lanka</option>
                                <option value="Sudan">Sudan</option>
                                <option value="Suriname">Suriname</option>
                                <option value="Swaziland">Swaziland</option>
                                <option value="Sweden">Sweden</option>
                                <option value="Switzerland">Switzerland</option>
                                <option value="Syria">Syria</option>
                                <option value="Tahiti">Tahiti</option>
                                <option value="Taiwan">Taiwan</option>
                                <option value="Tajikistan">Tajikistan</option>
                                <option value="Tanzania">Tanzania</option>
                                <option value="Thailand">Thailand</option>
                                <option value="Togo">Togo</option>
                                <option value="Tokelau">Tokelau</option>
                                <option value="Tonga">Tonga</option>
                                <option value="Trinidad & Tobago">Trinidad & Tobago</option>
                                <option value="Tunisia">Tunisia</option>
                                <option value="Turkey">Turkey</option>
                                <option value="Turkmenistan">Turkmenistan</option>
                                <option value="Turks & Caicos Is">Turks & Caicos Is</option>
                                <option value="Tuvalu">Tuvalu</option>
                                <option value="Uganda">Uganda</option>
                                <option value="United Kingdom">United Kingdom</option>
                                <option value="Ukraine">Ukraine</option>
                                <option value="United Arab Erimates">United Arab Emirates</option>
                                <option value="United States of America">United States of America</option>
                                <option value="Uraguay">Uruguay</option>
                                <option value="Uzbekistan">Uzbekistan</option>
                                <option value="Vanuatu">Vanuatu</option>
                                <option value="Vatican City State">Vatican City State</option>
                                <option value="Venezuela">Venezuela</option>
                                <option value="Vietnam">Vietnam</option>
                                <option value="Virgin Islands (Brit)">Virgin Islands (Brit)</option>
                                <option value="Virgin Islands (USA)">Virgin Islands (USA)</option>
                                <option value="Wake Island">Wake Island</option>
                                <option value="Wallis & Futana Is">Wallis & Futana Is</option>
                                <option value="Yemen">Yemen</option>
                                <option value="Zaire">Zaire</option>
                                <option value="Zambia">Zambia</option>
                                <option value="Zimbabwe">Zimbabwe</option>
                            </select>
                        </div>
                    </div>
                    <br><br> -->
                    <div class="form-group">
                        <label for="usercountry">Pays de résidence</label>
                        <input type="text" class="form-control" id="usercountry" name="usercountry" placeholder="Pays de résidence">
                    </div>
                    <div class="form-group">
                        <label for="usercountry">Ville</label>
                        <input type="text" class="form-control" id="usercity" name="usercity" placeholder="Ville">
                    </div>
                    <div class="form-group">
                        <label for="passwrd1">Mot de passe</label>
                        <input type="password" name="newpasswrd1" id="newpasswrd1" class="form-control" placeholder="Entrer un mot de passe">
                        <span class="text-red">8 caractères minimum</span>
                    </div>
                    <div class="form-group">
                        <label for="passwrd2">Confirm Password</label>
                        <input type="password" name="newpasswrd2" id="newpasswrd2" class="form-control" placeholder="Confirmer votre mot de passe">
                        <small class="red-texts" id="passmsg" style="display: none ;">Les mot de passes ne sont pas compatibles</small>
                    </div>
                    <div class="form-group">
                        <div class="d-flex align-items-center justify-content-between">
                            <div class="form-check">
                                <input type="checkbox" class="form-check-input" id="show-password" onclick="viewPasswrd()">
                                <label class="form-check-label" for="show-password">Voir Mot de passe</label>
                            </div>
                        </div>
                    </div>
                    <button type="button" class="default-btn" id="savebtn">
                        <i class="fa fa-spinner fa-pulse" id="spiniconadduser" style="display: none"></i>
                        <span id="btn-txt-adduser">Créer un compte</span>
                    </button>
                </form>
                <span class="dont-account">Vous aviez déja un compte? <a href="javascript:void(0)" data-dismiss="modal" data-toggle="tooltip" data-placement="top" title="Cliquer Ici pour vous connecter">Connecter vous maintenant!</a></span>
            </div>
        </div>
    </div>
</div>


<!--<div class="modal right fade shoppingCartModal" id="shoppingCartModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true"><i class='bx bx-x'></i></span>
            </button>
            <div class="modal-body">
                <h3>My Cart (3)</h3>
                
                <div class="products-cart-content">
                    <div class="products-cart d-flex align-items-center">
                        <div class="products-image">
                            <a href="single.html"><img src="<?= $iniObj->UIPath ?>/img/products/products-img1.jpg" alt="image"></a>
                        </div>
                        <div class="products-content">
                            <h3><a href="single.html">Infrared Thermometer Gun</a></h3>
                            <div class="products-price">
                                <span>1</span>
                                <span>x</span>
                                <span class="price">$69.00</span>
                            </div>
                        </div>
                        <a href="cart.html" class="remove-btn"><i class='bx bx-trash'></i></a>
                    </div>
                </div>
                <div class="products-cart-subtotal">
                    <span>Subtotal</span>
                    <span class="subtotal">$268.00</span>
                </div>
                <div class="products-cart-btn">
                    <a href="checkout.html" class="default-btn">Proceed to Checkout</a>
                </div>
            </div>
        </div>
    </div>
</div>-->


<div class="modal fade productsQuickView" id="productsQuickView" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true"><i class='bx bx-x'></i></span>
            </button>
            <div class="row align-items-center">
                <div class="col-lg-6 col-md-6">
                    <div class="products-image" id="">
                        <img src="<?= $iniObj->UIPath ?>/img/products/products-img1.jpg" id="itemImg" alt="item Image">
                    </div>
                </div>
                <div class="col-lg-6 col-md-6">
                    <div class="products-content">
                        <h3><a href="single.html" id="itemname"></a></h3>
                        <div class="products-review">
                            <div class="rating">
                                <i class='bx bxs-star'></i>
                                <i class='bx bxs-star'></i>
                                <i class='bx bxs-star'></i>
                                <i class='bx bxs-star'></i>
                                <i class='bx bxs-star'></i>
                            </div>
                            <a href="single.html" class="rating-count">(3 reviews)</a>
                        </div>
                        <div class="price">
                            $<span id="itemprice"></span>
                        </div>
                        <p id="itemdesc"></p>
                        <!-- <div class="products-add-to-cart">
                            <button type="submit" class="default-btn"><i class="flaticon-trolley addcart"></i> Ajouter au panier </button>
                        </div>-->
                        <ul class="social-share">
                            <li><span>Partager:</span></li>
                            <li><a href="#" target="#"><i class='bx bxl-facebook-square'></i></a></li>
                            <li><a href="#" target="#"><i class='bx bxl-twitter'></i></a></li>
                            <li><a href="#" target="#"><i class='bx bxl-instagram-alt'></i></a></li>
                            <li><a href="#" target="#"><i class='bx bxl-linkedin-square'></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="go-top"><i class='bx bx-up-arrow-alt'></i></div>
<script>
    $(document).on("ready", function() {
        toastr.options = {
            "closeButton": false,
            "debug": false,
            "newestOnTop": false,
            "progressBar": false,
            "positionClass": "toast-top-right",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        };

    })

    $("#savebtn").on("click", function() {
        // alert("Nice");
        //var email = encodeURIComponent($("input[name='newemail']").val());
        var lastname = $("input[name='newlastname']").val();
        var firstname = $("input[name='newfirstname']").val();
        var email = $("input[name='newemail']").val();
        var phone = $("input[name='newphone']").val();
        var password1 = $("input[name='newpasswrd1']").val();
        var password2 = $("input[name='newpasswrd2']").val();
        var country = $("input[name='usercountry']").val();
        var city = $("input[name='usercity']").val();
        $("#savebtn").attr("disabled", true);
        document.getElementById("spiniconadduser").style.display = "block";
        $("#btn-txt-adduser").text(" ..");

        $.ajax({
            type: "POST",
            url: "/saveUser",
            data: {
                lastname: lastname,
                firstname: firstname,
                email: email,
                phone: phone,
                password1: password1,
                password2: password2,
                country: country,
                city: city
            },
            // data: $("#addUser").serialize(),
            success: function(msg) {
                console.log(msg);
                var val = msg.split('||');
                if (val[0] == "true") {
                    $('#addUser').each(function() {
                        this.reset();
                    });
                    $("#registerModal").modal('hide');
                    $("#loginModal").modal('show');
                    $("#savebtn").attr("disabled", false);
                    document.getElementById("spiniconadduser").style.display = "none";
                    $("#btn-txt-adduser").text("Créer un compte");
                    $.notify(val[1], "success");
                } else if (val[0] == "false") {
                    $("#savebtn").attr("disabled", false);
                    document.getElementById("spiniconadduser").style.display = "none";
                    $("#btn-txt-adduser").text("Créer un compte");
                    $.notify(val[1], "error");
                }
            }
        });
        return false;
    });

    function loadItemdata(id) {
        //console.log(id);
        $.ajax({
            url: "/quickview",
            method: "POST",
            data: {
                get_data: 1,
                id: id
            },
            success: function(msg) {
                var val = msg.split('||');
                console.log(val)
                if (val[0] == "false") {
                    $("#error_message").html(val[1]);
                    $("#error_message").show();
                    $("#nextBtn").html("S'inscrire. ").attr("disabled", false);
                    $("#prevBtn").attr("disabled", false);
                    $("#prevBtn").show();
                } else if (val[0] == "true") {
                    $("#itemprice").html(val[1]);
                    $("#itemname").html(val[2]);
                    $("#itemdesc").html(val[3]);
                    $("#itemid").html(val[4]);
                    document.getElementById("itemImg").src = (val[5]);
                    //$("#itemImg").html(val[5]);
                    $("#productsQuickView").modal("show");

                }


            },
            error: function(resultat, statut, erreur) {

                // $("#submit_user").html("S'inscrire' <i class='fa fa-user'></i>")
                //     .attr("disabled", false);
                $("#error_message").html("Une erreur s'est produite. Veuillez réessayer. <i class='fa fa-stop-circle'></i>");
                console.log('Resultat : ' + resultat);
                console.log('Statut : ' + statut);
                console.log('Erreur : ' + erreur);
            }
        });
    }

    function viewPasswrd() {
        var pass1 = document.getElementById("newpasswrd1");
        var pass2 = document.getElementById("newpasswrd2");
        if (pass1.type === "password" && pass2.type === "password") {
            pass1.type = "text";
            pass2.type = "text";
        } else {
            pass1.type = "password";
            pass2.type = "password";
        }
    }

    function viewLoginPass() {
        var password = document.getElementById("password");
        if (password.type === "password") {
            password.type = "text";
        } else {
            password.type = "password";
        }
    }


    $("#userlogin").on("submit", function() {

        var email = $("input[name='email']").val();
        var pass = $("input[name='password']").val();

        //console.log(email, pass);
        $.ajax({
            type: "POST",
            url: "/custConnect",
            data: {
                email: email,
                pass: pass
            },
            success: function(msg) {
                console.log(msg);
                var val = msg.split("||");
                if (val[0] == "true") {
                    location.reload();
                } else if (val[0] == "false") {
                    $.notify(val[1], "error");
                    //$("#error_msg").html(val[1]);
                }
            }
        });

        return false;
    });

    $("#userlogout").on("click", function() {
        $.ajax({
            type: "POST",
            url: "/userlogout",
            success: function(msg) {
                console.log(msg);
                var val = msg.split("||");
                if (val[0] == "true") {
                    location.reload();
                } else if (val[0] == "false") {
                    $.notify(val[1], "error");
                }
            }
        });
    });

    $(".addcart").on("click", function() {
        // alert('oui')
        var itemid = $(this).attr("id");
        $.ajax({
            type: "POST",
            //url: "/addCart",
            url: "/addTocart",
            data: {
                itemid: itemid
            },
            success: function(msg) {
                console.log(msg);
                var val = msg.split("||");
                if (val[0] == "true") {
                    //cartnumber();
                    $("#cart_coount").html(val[2]);
                    $.notify(val[1], "success");

                } else if (val[0] == "false") {
                    $.notify(val[1], "error");
                    $("#loginModal").modal();
                    $.notify(val[1], "error");
                }
            }
        });
    });

    $("#search_form").on("submit", function() {
        //alert("OK");
        var key = $("input[name='key']").val();
        window.location.replace("/searchpage_" + key);
        /*$.ajax({
            url : "/searchpage",
            method : "POST",
            data : {
                key : key
            },
            success : function(){

            }
        })*/
        return false;
    })
</script>
<script>


</script>