<?php
$userinfo = $sqlData->getUserinfo($_SESSION['customer']['contact_id']);
// $lib->debug($userinfo);
// exit;
?>

<body>

    <!-- Begin page -->
    <div id="layout-wrapper">

        <header id="page-topbar">
            <div class="navbar-header">

                <div class="d-flex align-items-left">
                    <?php if ($_SESSION['customer']['role_id'] == 1) : ?>
                        <button type="button" class="btn btn-sm mr-2 d-lg-none px-3 font-size-16 header-item waves-effect" id="vertical-menu-btn">
                            <i class="fa fa-fw fa-bars"></i>
                        </button>

                        <div class="dropdown d-none d-sm-inline-block">
                            <button type="button" class="btn header-item waves-effect" id="page-header-user-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="mdi mdi-plus"></i> Créer
                                <i class="mdi mdi-chevron-down d-none d-sm-inline-block"></i>
                            </button>
                            <div class="dropdown-menu">

                                <!-- item-->
                                <a href="javascript:void(0);" class="dropdown-item notify-item">
                                    Article
                                </a>

                                <!-- item-->
                                <a href="/customer/categories" class="dropdown-item notify-item">
                                    Catégorie
                                </a>

                                <!-- item-->
                                <a href="javascript:void(0);" class="dropdown-item notify-item">
                                    Utilisateur
                                </a>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>

                <div class="d-flex align-items-center">

                    <!--<div class="dropdown d-none d-sm-inline-block ml-2">
                        <button type="button" class="btn header-item noti-icon waves-effect" id="page-header-search-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="mdi mdi-magnify"></i>
                        </button>
                        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right p-0" aria-labelledby="page-header-search-dropdown">

                            <form class="p-3">
                                <div class="form-group m-0">
                                    <div class="input-group">
                                        <input type="text" class="form-control" placeholder="Search ..." aria-label="Recipient's username">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="submit"><i class="mdi mdi-magnify"></i></button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>-->

                    <!--<div class="dropdown d-inline-block">
                        <button type="button" class="btn header-item waves-effect" id="page-header-user-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <img class="" src="<?= $iniObj->UIPath ?>/backoffice/images/flags/us.jpg" alt="Header Language" height="16">
                            <span class="d-none d-sm-inline-block ml-1">English</span>
                            <i class="mdi mdi-chevron-down d-none d-sm-inline-block"></i>
                        </button>
                        <div class="dropdown-menu dropdown-menu-right">

                            
                            <a href="javascript:void(0);" class="dropdown-item notify-item">
                                <img src="<?= $iniObj->UIPath ?>/backoffice/images/flags/spain.jpg" alt="user-image" class="mr-1" height="12">
                                <span class="align-middle">Spanish</span>
                            </a>

                            
                            <a href="javascript:void(0);" class="dropdown-item notify-item">
                                <img src="<?= $iniObj->UIPath ?>/backoffice/images/flags/germany.jpg" alt="user-image" class="mr-1" height="12">
                                <span class="align-middle">German</span>
                            </a>

                            
                            <a href="javascript:void(0);" class="dropdown-item notify-item">
                                <img src="<?= $iniObj->UIPath ?>/backoffice/images/flags/italy.jpg" alt="user-image" class="mr-1" height="12">
                                <span class="align-middle">Italian</span>
                            </a>

                            
                            <a href="javascript:void(0);" class="dropdown-item notify-item">
                                <img src="<?= $iniObj->UIPath ?>/backoffice/images/flags/russia.jpg" alt="user-image" class="mr-1" height="12">
                                <span class="align-middle">Russian</span>
                            </a>
                        </div>
                    </div>-->

                    <!--<div class="dropdown d-inline-block">
                        <button type="button" class="btn header-item noti-icon waves-effect" id="page-header-notifications-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="mdi mdi-bell"></i>
                            <span class="badge badge-danger badge-pill">0</span>
                        </button>
                        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right p-0" aria-labelledby="page-header-notifications-dropdown">
                            <div class="p-3">
                                <div class="row align-items-center">
                                    <div class="col">
                                        <h6 class="m-0"> Notifications </h6>
                                    </div>
                                    <div class="col-auto">
                                        <a href="#!" class="small"> View All</a>
                                    </div>
                                </div>
                            </div>
                            <div data-simplebar style="max-height: 230px;">
                                <!--<a href="#" class="text-reset notification-item">
                                    <div class="media">
                                        <div class="avatar-xs mr-3">
                                            <span class="avatar-title bg-success rounded-circle">
                                                <i class="mdi mdi-cloud-download-outline"></i>
                                            </span>
                                        </div>
                                        <div class="media-body">
                                            <h6 class="mt-0 mb-1">Download Available !</h6>
                                            <p class="font-size-13 mb-1">Latest version of admin is now available.
                                                Please download here.</p>
                                            <p class="font-size-12 mb-0 text-muted"><i class="mdi mdi-clock-outline"></i> 4 hours ago</p>
                                        </div>
                                    </div>
                                </a>
                                <a href="#" class="text-reset notification-item">
                                    <div class="media">
                                        <img src="<?= $iniObj->UIPath ?>/backoffice/images/users/avatar-3.jpg" class="mr-3 rounded-circle avatar-xs" alt="user-pic">
                                        <div class="media-body">
                                            <h6 class="mt-0 mb-1">Victoria Mendis</h6>
                                            <p class="font-size-13 mb-1">Just upgraded to premium account.</p>
                                            <p class="font-size-12 mb-0 text-muted"><i class="mdi mdi-clock-outline"></i> 1 day ago</p>
                                        </div>
                                    </div>
                                </a>
                                <a href="javascrip:void(0)" class="text-reset notification-item">Aucune notification</a>
                            </div>
                            <div class="p-2 border-top">
                                <a class="btn btn-sm btn-light btn-block text-center" href="javascript:void(0)">
                                    <i class="mdi mdi-arrow-down-circle mr-1"></i> Plus..
                                </a>
                            </div>
                        </div>
                    </div>-->

                    <div class="dropdown d-inline-block ml-2">
                        <button type="button" class="btn header-item waves-effect" id="page-header-user-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <?php if ($_SESSION['customer']['img']) { ?>
                                <img class="rounded-circle header-profile-user" src="<?= $iniObj->imgProfilePath . $userinfo['data'][0]->img ?>" alt="Header Avatar">
                            <?php } else { ?>
                                <img class="rounded-circle header-profile-user" src="<?= $iniObj->UIPath ?>/uploads/user.jpg" alt="Header Avatar">
                            <?php } ?>
                            <span class="d-none d-sm-inline-block ml-1"><?= ucfirst($userinfo['data'][0]->fisrtname) . ' ' . ucfirst(substr($userinfo['data'][0]->lastname, 0, 1)) ?>.</span>
                            <i class="mdi mdi-chevron-down d-none d-sm-inline-block"></i>
                        </button>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a class="dropdown-item d-flex align-items-center justify-content-between" href="<?= $iniObj->siteUrl ?>">
                                <span>Revenir à l'acceuil</span>
                            </a>
                            <a class="dropdown-item d-flex align-items-center justify-content-between" href="/shop">
                                <span>Boutique</span>
                            </a>
                            <a class="dropdown-item d-flex align-items-center justify-content-between" href="/customer/userprofile">
                                <span>Paramettres</span>
                            </a>
                            <a class="dropdown-item d-flex align-items-center justify-content-between" href="/userlogout">
                                <span>Déconnexion</span>
                            </a>
                        </div>
                    </div>

                </div>
            </div>
        </header>