<!-- ========== Left Sidebar Start ========== -->
<div class="vertical-menu">

    <div data-simplebar class="h-100">

        <!-- <div class="navbar-brand-box">
            <a href="index.html" class="logo">
                <img src="<?= $iniObj->UIPath ?>/backoffice/images/logo-light.png" />
            </a>
        </div> -->

        <!--- Sidemenu -->
        <div id="sidebar-menu">
            <!-- Left Menu Start -->
            <ul class="metismenu list-unstyled" id="side-menu">
                <li class="menu-title">Menu de Navigation</li>

                <li>
                    <a href="/dashboard" class="waves-effect"><i class='bx bx-home-smile'></i><span>Tableau de Bord</span></a>
                </li>
                <?php if ($_SESSION['customer']['role_id'] == 1) : ?>
                    <li><a href="/customer/categories" class="waves-effect"><i class="bx bx-file"></i><span>Catégories</span></a></li>

                    <li>
                        <a href="javascript: void(0);" class="has-arrow waves-effect"><i class="bx bxl-product-hunt"></i><span>Produits</span></a>
                        <ul class="sub-menu" aria-expanded="false">
                            <li><a href="/customer/products">Tous les Produits</a></li>
                            <li><a href="/customer/newproduct">Nouveau Produit</a></li>
                            <li><a href="javascript:void(0)">Nos Marque</a></li>
                        </ul>
                    </li>
                    <li><a href="/customer/inventory" class="waves-effect"><i class="bx bx-file"></i><span>Inventaire</span></a></li>
                <?php endif; ?>



                <li><a href="/customer/delivery" class=" waves-effect"><i class="bx bx-calendar"></i><span>Livraisons</span></a></li>
                <li><a href="/customer/orders" class=" waves-effect"><i class="bx bx-calendar"></i><span>Commandes</span></a></li>
                <?php if ($_SESSION['customer']['role_id'] == 1) : ?>

                    <li>
                        <a href="javascript: void(0);" class="has-arrow waves-effect"><i class="bx bx-user"></i><span>Utilisateurss</span></a>
                        <ul class="sub-menu" aria-expanded="false">
                            <li><a href="/customer/users">Tous les Utilisateurs</a></li>
                            <li><a href="/customer/userroles">Les groupes d'Utisateurs</a></li>
                        </ul>
                    </li>
                <?php endif; ?>
            </ul>
        </div>
        <!-- Sidebar -->
    </div>
</div>
<!-- Left Sidebar End -->