<?php
if ($iniObj->debugViews)
    echo __FILE__;
$title = "Tableau de board  || ".$iniObj->serviceName;
include _VIEW_PATH . '/dashboard_head.phtml';
include _VIEW_PATH . $lib->lang . '/dashboard_header.phtml';
include _VIEW_PATH . $lib->lang . '/dashboard_sidebar.phtml';
?>

<!-- ============================================================== -->
<!-- Start right Content here -->
<!-- ============================================================== -->
<div class="main-content">

    <div class="page-content">
        <div class="container-fluid">

            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box d-flex align-items-center justify-content-between">
                        <h4 class="mb-0 font-size-18">Tableau de bord</h4>


                    </div>
                </div>
            </div>
            <!-- end page title -->



        </div> <!-- container-fluid -->
        <?php if ($_SESSION['customer']['role_id'] == 1) : ?>
            <div class="row">
                <div class="col-xl-3 col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <i class="bx bx-dollar-circle float-right m-0 h2 text-muted"></i>
                            <h6 class="text-muted text-uppercase mt-0">Commandes en cours de traitement</h6>
                            <h3 class="mb-3" data-plugin="counterup"><?= ($orderInprogress['rows'] == 0) ? "0" : $orderInprogress['rows'] ?></h3>
                            <!--<span class="badge badge-success mr-1"> +11% </span> <span class="text-muted">From previous period</span>-->
                        </div>
                    </div>
                </div>

                <div class="col-xl-3 col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <i class="bx bx-basket float-right m-0 h2 text-muted"></i>
                            <h6 class="text-muted text-uppercase mt-0">Paiement en cours</h6>
                            <h3 class="mb-3"><span data-plugin="counterup"><?= ($payment["rows"] == 0) ? "0" : $payment["rows"] ?></span></h3>
                            <!--<span class="badge badge-danger mr-1"> -29% </span> <span class="text-muted">From previous period</span>-->
                        </div>
                    </div>
                </div>

                <div class="col-xl-3 col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <i class="bx bxl-product-hunt float-right m-0 h2 text-muted"></i>
                            <h6 class="text-muted text-uppercase mt-0">Produits</h6>
                            <h3 class="mb-3"><span data-plugin="counterup"><?= ($allproducts["rows"] == 0) ? "0" : $allproducts["rows"] ?></span></h3>
                            <!--<span class="badge badge-warning mr-1"> 0% </span> <span class="text-muted">From previous period</span>-->
                        </div>
                    </div>
                </div>

                <div class="col-xl-3 col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <i class="bx bx-user float-right m-0 h2 text-muted"></i>
                            <h6 class="text-muted text-uppercase mt-0">CLients</h6>
                            <h3 class="mb-3" data-plugin="counterup"><?= ($customers["rows"] == 0) ? "0" : $customers["rows"] ?></h3>
                            <!-- <span class="badge badge-success mr-1"> +89% </span> <span class="text-muted">Last year</span>-->
                        </div>
                    </div>
                </div>
            </div>
            <!-- end row -->
        <?php endif; ?>



        <?php if ($_SESSION['customer']['role_id'] == 2) : ?>
            <div class="row">
                <div class="col-xl-3 col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <i class="bx bx-dollar-circle float-right m-0 h2 text-muted"></i>
                            <h6 class="text-muted text-uppercase mt-0">Commandes en cours</h6>
                            <h3 class="mb-3" data-plugin="counterup"><?= $customOrders['rows'] ?></h3>
                            <a href="/customer/orders"> <span class="text-muted">Détails <i class="fa fa-arrow-right"></i></span> </a>
                        </div>
                    </div>
                </div>

                <div class="col-xl-3 col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <i class="bx bx-basket float-right m-0 h2 text-muted"></i>
                            <h6 class="text-muted text-uppercase mt-0">Livraisons</h6>
                            <h3 class="mb-3"><span data-plugin="counterup">0</span></h3>
                            <!-- <span class="badge badge-danger mr-1"> -29% </span> <span class="text-muted">From previous period</span> -->
                        </div>
                    </div>
                </div>
            </div>
            <!-- end row -->
        <?php endif; ?>




        <!-- End Page-content -->



        <?php
        include _VIEW_PATH . $lib->lang . '/dashboard_footer.phtml';
        include _VIEW_PATH . 'dashboard_include_files.phtml';
        ?>