<section class="home-slides owl-carousel owl-theme">
    <div class="single-banner-item">
        <div class="container-fluid">
            <div class="row align-items-center">
                <div class="col-lg-6 col-md-12">
                    <div class="banner-content">
                        <span class="sub-title">SAVE UP TO 40%</span>
                        <h1>Digital Blood Pressure Machine</h1>
                        <a href="/shop" class="default-btn"><i class="flaticon-trolley"></i> Shop Now</a>
                    </div>
                </div>
                <div class="col-lg-6 col-md-12">
                    <div class="banner-image text-center">
                        <img src="<?= $iniObj->UIPath ?>/img/banner/banner-img1.png" class="main-image" alt="image">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="single-banner-item">
        <div class="container-fluid">
            <div class="row align-items-center">
                <div class="col-lg-6 col-md-12">
                    <div class="banner-content">
                        <span class="sub-title">DERNIERS ARRIVAGES</span>
                        <h1>Electronic Glucometer</h1>
                        <a href="/shop" class="default-btn"><i class="flaticon-trolley"></i> Shop Now</a>
                    </div>
                </div>
                <div class="col-lg-6 col-md-12">
                    <div class="banner-image text-center">
                        <img src="<?= $iniObj->UIPath ?>/img/banner/banner-img2.png" class="main-image" alt="image">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="single-banner-item">
        <div class="container-fluid">
            <div class="row align-items-center">
                <div class="col-lg-6 col-md-12">
                    <div class="banner-content">
                        <span class="sub-title">SAVE UP TO 40%</span>
                        <h1>Protective Hand Gloves</h1>
                        <a href="/shop" class="default-btn"><i class="flaticon-trolley"></i> Shop Now</a>
                    </div>
                </div>
                <div class="col-lg-6 col-md-12">
                    <div class="banner-image text-center">
                        <img src="<?= $iniObj->UIPath ?>/img/banner/banner-img3.png" class="main-image" alt="image">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<section class="products-area ptb-70">
    <div class="container">
        <div class="row">
            <div class="col-xl-3 col-lg-4 col-md-12">
                <div class="woocommerce-widget-area">
                    <div class="megamenu-container megamenu-container2">
                        <div class="megamenu-title">
                            <i class='bx bx-category'></i> Catégories
                        </div>
                        <div class="megamenu-category">
                            <ul class="nav">
                                <?php foreach ($categories['data'] as $key => $category) : ?>
                                    <li class="nav-item"><a href="/category_<?= $category->category_id ?>" class="nav-link"><?= $category->name ?></a></li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    </div>
                    <div class="woocommerce-widget price-list-widget">
                        <!-- <h3 class="woocommerce-widget-title">Filter By Price</h3>
                        <div class="collection-filter-by-price">
                            <input class="js-range-of-price" type="text" data-min="0" data-max="1055" name="filter_by_price" data-step="10">
                            <button type="submit">Filter</button>
                        </div> -->
                    </div>
                    <div class="woocommerce-widget best-seller-widget">
                        <!-- <h3 class="woocommerce-widget-title">Best Seller</h3>
                        <article class="item">
                            <a href="single.html" class="thumb">
                                <span class="fullimage cover bg1" role="img"></span>
                            </a>
                            <div class="info">
                                <h4 class="title usmall"><a href="single.html">Thermometer Gun</a></h4>
                                <span>$139.00</span>
                                <div class="rating">
                                    <i class='bx bxs-star'></i>
                                    <i class='bx bxs-star'></i>
                                    <i class='bx bxs-star'></i>
                                    <i class='bx bxs-star'></i>
                                    <i class='bx bxs-star'></i>
                                </div>
                            </div>
                            <div class="clear"></div>
                        </article> -->
                        <!-- <article class="item">
                            <a href="single.html" class="thumb">
                                <span class="fullimage cover bg2" role="img"></span>
                            </a>
                            <div class="info">
                                <h4 class="title usmall"><a href="single.html">Hand Sanitizer</a></h4>
                                <span>$25.00</span>
                                <div class="rating">
                                    <i class='bx bxs-star'></i>
                                    <i class='bx bxs-star'></i>
                                    <i class='bx bxs-star'></i>
                                    <i class='bx bxs-star'></i>
                                    <i class='bx bxs-star-half'></i>
                                </div>
                            </div>
                            <div class="clear"></div>
                        </article> -->
                        <!-- <article class="item">
                            <a href="single.html" class="thumb">
                                <span class="fullimage cover bg3" role="img"></span>
                            </a>
                            <div class="info">
                                <h4 class="title usmall"><a href="single.html">Medical Mask</a></h4>
                                <span>$19.00</span>
                                <div class="rating">
                                    <i class='bx bxs-star'></i>
                                    <i class='bx bxs-star'></i>
                                    <i class='bx bxs-star'></i>
                                    <i class='bx bxs-star'></i>
                                    <i class='bx bx-star'></i>
                                </div>
                            </div>
                            <div class="clear"></div>
                        </article> -->
                    </div>
                    <div class="woocommerce-widget woocommerce-ads-widget">
                        <!-- <a href="#" class="d-inline-block">
                            <img src="<?= $iniObj->UIPath ?>/img/ads.jpg" alt="image">
                        </a>
                        <div class="content">
                            <h4>New Collection Glucose Device Meter</h4>
                            <span>Stock is limited..!</span>
                            <a href="products-left-sidebar.html" class="link-btn"><i class="flaticon-trolley"></i>
                                Shop Now</a>
                        </div> -->
                    </div>
                </div>
            </div>
            <div class="col-xl-9 col-lg-8 col-md-12">
                <div class="theme-grid-sorting">
                    <div class="row align-items-center">
                        <div class="col-lg-6 col-md-6 result-count">
                            <!--<p>Showing 1 to 12 of 20</p>-->
                        </div>
                        <div class="col-lg-6 col-md-6 ordering">
                            <div class="select-box">
                                <!-- <label>Sort By:</label>
                                <select>
                                    <option>Default</option>
                                    <option>Popularity</option>
                                    <option>Latest</option>
                                    <option>Price: low to high</option>
                                    <option>Price: high to low</option>
                                </select>-->
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <?php foreach ($items['data'] as $key => $item) : ?>
                        <div class="col-xl-4 col-lg-6 col-md-4 col-sm-6">
                            <div class="single-products-box">
                                <div class="image">
                                    <a href="/product_<?= $item->item_id ?>" class="d-block">
                                        <?php
                                        $itemImg = $sqlData->getItemFeaImg($item->item_id);
                                        if ($itemImg['data'][0]->path) { ?>
                                            <img src="<?= $iniObj->imgPath . $itemImg['data'][0]->path ?>" alt="image">
                                        <?php } else { ?>
                                            <img src="<?= $iniObj->UIPath ?>/img/products/products-img1.jpg" alt="image">
                                        <?php  } ?>
                                    </a>
                                    <div class="new">New</div>
                                    <ul class="buttons-list">
                                        <li>
                                            <a href="javascript:void(0)" id="<?= $item->item_id ?>" class="addcart">
                                                <i class='bx bxs-cart-add'></i>
                                                <span class="tooltip-label">Ajouter au panier</span>
                                                <input type="hidden" value="1" id="quantity">
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#" data-id="<?= $item->item_id ?>" class="quickview" onclick="loadItemdata(this.getAttribute('data-id'))" data-toggle="modal" data-target="">
                                                <i class='bx bx-search-alt'></i>
                                                <span class="tooltip-label">Voir</span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                                <div class="content">
                                    <div class="rating">
                                        <i class='bx bxs-star'></i>
                                        <i class='bx bxs-star'></i>
                                        <i class='bx bxs-star'></i>
                                        <i class='bx bxs-star'></i>
                                        <i class='bx bxs-star'></i>
                                    </div>
                                    <h3><a href="single.html"><?= $item->name ?></a></h3>
                                    <div class="price">
                                        <span class="new-price">€<?= $item->price_max ?></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>

                    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
                        <div class="pagination-area text-center">
                            <?= $pagination->paginate($pages_requested, $currentPage); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>