<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0"><?= $lang->trl('Dashboard') ?></h1>
        </div>
        <!-- <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">Tableau de bord</li>
          </ol>
        </div> -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
  <!-- /.content-header -->

  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <!-- Small boxes (Stat box) -->
      <div class="row">
        <div class="col-lg-4 col-6">
          <!-- small box -->
          <div class="small-box bg-info">
            <div class="inner">
              <h3><?= $allcontact ?></h3>

              <p><?= $lang->trl('Contacts') ?></p>
            </div>
            <div class="icon">
              <i class="fa fa-id-card-alt"></i>
            </div>
            <a href="/customer/contact_list" class="small-box-footer"><?= $lang->trl('See More') ?> <i class="fas fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <div class="col-lg-4 col-6">
          <!-- small box -->
          <div class="small-box bg-warning">
            <div class="inner">
              <h3><?= $allmission ?></h3>

              <p><?= $lang->trl('Missions') ?></p>
            </div>
            <div class="icon">
              <i class="fa fa-tasks"></i>
            </div>
            <a href="/customer/mission_list/" class="small-box-footer"><?= $lang->trl('See More') ?> <i class="fas fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-4 col-6">
          <!-- small box -->
          <div class="small-box bg-danger">
            <div class="inner">
              <h3><?= $allcompanies ?></h3>

              <p><?= $lang->trl('Companies') ?></p>
            </div>
            <div class="icon">
              <i class="fa fa-building"></i>
            </div>
            <a href="/customer/company_list/" class="small-box-footer"><?= $lang->trl('See More') ?> <i class="fas fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <!-- ./col -->
      </div>
      <!-- /.row -->
      <!-- Main row -->
      <div class="row">
        <!-- Left col -->
        <?php if ($_SESSION['customer']['role_id'] == 1) : ?>
          <div class="col-lg-6">
            <div class="card">
              <div class="card-header border-0">
                <h3 class="card-title"><?= $lang->trl('Recent Addition') ?>( <?= $lang->trl('Contacts') ?> )</h3>
                <!-- <div class="card-tools">
                  <a href="#" class="btn btn-tool btn-sm">
                    <i class="fas fa-download"></i>
                  </a>
                  <a href="#" class="btn btn-tool btn-sm">
                    <i class="fas fa-bars"></i>
                  </a>
                </div> -->
              </div>
              <div class="card-body table-responsive p-0">
                <table class="table table-striped table-valign-middle">
                  <thead>
                    <tr>
                      <th><?= $lang->trl('Full Name') ?></th>
                      <th><?= $lang->trl('Companies') ?></th>
                      <th><?= $lang->trl('Added by') ?> </th>
                      <th><?= $lang->trl('Added on') ?> </th>
                    </tr>
                  </thead>
                  <tbody>
                    <?php foreach ($contacts as $key => $contact) : ?>
                      <tr>
                        <td>
                          <?= ucfirst($contact->contact_firstname) . ' ' . ucfirst($contact->contact_lastname) ?>
                        </td>
                        <td><?= ucfirst($contact->company) ?></td>
                        <td>
                          <?= ucfirst($contact->user_firstname) . ' ' . ucfirst($contact->user_lastname) ?>
                        </td>
                        <td>
                          <?= $sqlData->refomat_date($contact->created_date) ?>
                        </td>
                      </tr>
                    <?php endforeach; ?>
                  </tbody>
                </table>
              </div>
            </div>
            <!-- /.card -->
          </div>
        <?php endif; ?>
        <div class="col-lg-6">
          <div class="card">
            <div class="card card-primary">
              <div class="card-body p-0">
                <!-- THE CALENDAR -->
                <div id="calendar"></div>
              </div>
              <!-- /.card-body -->
            </div>
          </div>
        </div>
        <!-- /.card -->

      </div>

      <!-- /.card -->
      <!-- /.row (main row) -->
    </div><!-- /.container-fluid -->
  </section>
  <!-- /.content -->
</div>
<!-- /.content-wrapper -->

</div>
<!-- ./wrapper -->

