<div class="navbar-area navbar-style-two">
    <div class="theme-responsive-nav">
        <div class="container">
            <div class="theme-responsive-menu">
                <div class="logo">
                    <a href="index-3.html">
                        <img src="<?= $iniObj->UIPath ?>/img/logo.png" alt="logo">
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="theme-nav">
        <div class="container">
            <nav class="navbar navbar-expand-md navbar-light">
                <a class="navbar-brand" href="index.html">
                    <img src="<?= $iniObj->UIPath ?>/img/logo.png" alt="logo">
                </a>
                <div class="collapse navbar-collapse mean-menu">
                    <ul class="navbar-nav">
                        <li class="nav-item"><a href="javascript:void(0)" class="nav-link">Strudture Chimique</a>
                        </li>
                        <li class="nav-item"><a href="javascript:void(0)" class="nav-link">Demande de
                                Certificats</a></li>
                        <li class="nav-item"><a href="javascript:void(0)" class="nav-link">Fiche de sécurité</a>
                        </li>
                        <li class="nav-item"><a href="javascript:void(0)" class="nav-link">Suivi de commande</a>
                        </li>
                        <li class="nav-item"><a href="javascript:void(0)" class="nav-link">Offres</a></li>
                    </ul>
                    <div class="others-option d-flex align-items-center">
                        <div class="option-item">
                            <?php if ($_SESSION['customer']['authValidated']) : ?>
                                <div class="cart-btn">
                                    <a href="/cart" data-toggle="" data-target=""><i class='bx bx-cart'></i><span class="cart_icon"></span></a>
                                </div> <!--$cartdetail['rows']-->
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </nav>
        </div>
    </div>
</div>