<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><?= $iniObj->serviceName ?></title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/plugins/fontawesome-free/css/all.min.css">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/dist/css/adminlte.min.css">  
  <!-- Toastr -->
  <link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/plugins/toastr/toastr.min.css">
  <!-- jQuery -->
  <script src="<?php echo $iniObj->UIPath; ?>/plugins/jquery/jquery.min.js"></script>
</head>

<body class="hold-transition login-page">

  <?php
  include _VIEW_PATH . $lib->lang . "/login_content.phtml";
  ?>

  <?php //include _VIEW_PATH.$lib->lang."/common_footer.phtml";
  ?>

  <?php include _VIEW_PATH . "/common_include_files.phtml"; ?>

</body>