<div class="login-box">
  <div class="login-logo">
    <a href="#"><b>DKO</b>CRM</a>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg"><?= $lang->trl('Sign in to start your session') ?></p>
      <!-- <form action="/login" method="post"> -->
      <form action="" method="">
        <div class="input-group mb-3">
          <input type="email" id="email" name="email" class="form-control" placeholder="<?= $lang->trl('Email') ?>">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" id="password" name="password" class="form-control" placeholder="<?= $lang->trl('Password') ?>">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="form-check">
          <input type="checkbox" class="form-check-input" id="exampleCheck1" onclick="togglePass()">
          <label class="form-check-label" for="exampleCheck1"><?= $lang->trl('Display Password') ?></label>
        </div>
        <div class="row">

          <!-- <div class="col-8">
            <div class="icheck-primary">
              <input type="checkbox" id="remember">
              <label for="remember">
                Remember Me
              </label>
            </div>
          </div>  -->
          <!-- /.col -->
          <div class="col-6">
            <button type="submit" id="sbmitbtn" class="btn btn-primary"><?= $lang->trl('Log in') ?></button>
          </div>
          <!-- /.col -->
        </div>
      </form>

      <!-- <div class="social-auth-links text-center mb-3">
        <p>- OR -</p>
        <a href="#" class="btn btn-block btn-primary">
          <i class="fab fa-facebook mr-2"></i> Sign in using Facebook
        </a>
        <a href="#" class="btn btn-block btn-danger">
          <i class="fab fa-google-plus mr-2"></i> Sign in using Google+
        </a>
      </div> -->
      <!-- /.social-auth-links -->

      <p class="mb-1">
        <a href="/resetpass"><?= $lang->trl('I forgot my password') ?></a>
      </p>

    </div>
    <!-- /.login-card-body -->
  </div>
</div>

<script>
  function togglePass() {
    // console.log("ok")
    var pass1 = document.getElementById("password");
    if (pass1.type === "password") {
      pass1.type = "text";
    } else {
      pass1.type = "password";
    }
  }


  $("#sbmitbtn").on("click", function() {
    var email = document.getElementById("email").value;
    var password = document.getElementById("password").value;
    //console.log(email, password)
    $.ajax({
      type: "POST",
      url: "/login",
      data: {
        email: email,
        password: password
      },
      success: function(msg) {
        console.log(msg);
        var val = msg.split("||");
        if (val[0] == "false") {
          toastr["error"](val[1]);
        } else if (val[0] == "true") {
          window.location.href = '/customer/dashboard/';
        }
      }
    });
    return false;
  })
</script>