<?php

if ($iniObj->debugViews)
    echo __FILE__;
//$carouselActive = true;
$title = "Commande N° " . $order->code." || ".$iniObj->serviceName;
include _VIEW_PATH . "/customer_common_header.phtml";
?>

<?php
include _VIEW_PATH . "/customer_common_top_bar.phtml";
?>

<?php
include _VIEW_PATH . $lib->lang . "/customer_menu.phtml";
?>

<?php if ($orders['rows'] == 0) : ?>
    <section class="error-area ptb-70">
        <div class="container">
            <div class="error-content">
                <h3>Aucune Commande trouvée</h3>
                <p>(ou vérifier votre adresse email ou le code de la commande)</p>
                <a href="/tracking" class="default-btn"><i class="flaticon-left-chevron"></i> Retour </a>
            </div>
        </div>
    </section>
<?php endif; ?>


<?php if ($orders['rows'] == 1) : ?>
    <section class="page-title-area">
        <div class="container">
            <div class="page-title-content">
                <h1>Commande N° <?= $order->code ?> </h1>
                <p>
                    <?php
                    if ($order->status == 0) {
                        echo '<span class="badge bg-danger"> Commande rejetée </span>';
                    } else if ($order->status == 1) {
                        echo '<span class="badge bg-success"> Commande acceptée </span>';
                    } else if ($order->status == 2) {
                        echo '<span class="badge bg-warning"> Commande en cours de traitement </span>';
                    }else if($order->status == 4){
                        echo '<span class="badge bg-default"> Paiement en cours </span>';
                    }
                    ?>
                </p>
            </div>
        </div>
    </section>


    <section class="order-tracking-area ptb-70">
        <div class="container">
            <div class="row">

                <div class="col-lg-6 col-sm-16 col-md-12">
                    <div class="">
                        <h3> <?= ucfirst($ceckuser->lastname) . ' ' . ucfirst($ceckuser->fisrtname) ?> </h3>
                        <p><?= $ceckuser->email ?> </p>
                        <p><?= $ceckuser->phone ?> </p>
                        <p> <?= $ceckuser->city . ' ' . $ceckuser->country ?> </p>
                    </div>
                </div>
                <div class="col-lg-6 col-sm-16 col-md-12">
                    <div class="">
                        <?php if ($order->status == 1) { ?>
                            <h3>Adresse de Livraison</h3>
                            <p><?= $shippin_adress->street ?> </p>
                            <p><?= $shippin_adress->city ?> </p>
                            <p><?= $shippin_adress->country ?></p>
                        <?php } else { ?>
                            <p>Pas de livraison programmée pour cette commande</p>
                        <?php } ?>
                    </div>
                </div>
            </div>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">Articles</th>
                        <th scope="col">Prix Unitaire</th>
                        <th scope="col">Qty</th>
                        <th scope="col">Total</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($oderdetails['data'] as $keys => $detail) : ?>
                        <tr>
                            <th scope="row"><?= $detail->itemname ?></th>
                            <td><?= $detail->itemprice ?></td>
                            <td><?= $detail->quantity ?></td>
                            <td><?= intval($detail->itemprice) * intval($detail->quantity) ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
            <div class="row">
                <div class="col-lg-6 col-sm-16 col-md-12">
                </div>
                <div class="col-lg-6 col-sm-16 col-md-12">
                    <div class="">
                        <p>Total : <?= $order->total ?></p>
                        <p>Tax : </p>
                        <h3>Prix Total : <?= $order->total ?></h3>
                    </div>
                </div>
            </div>
        </div>
    </section>
<?php endif; ?>

<?php include _VIEW_PATH . $lib->lang . "/customer_common_footer.phtml"; ?>
<?php include _VIEW_PATH . "/customer_common_include_files.phtml"; ?>