<?php

if ($iniObj->debugViews)
    echo __FILE__;
$title = $item->name . " || ".$iniObj->serviceName;
include _VIEW_PATH . "/customer_common_header.phtml";
include _VIEW_PATH . "/customer_common_top_bar.phtml";
include _VIEW_PATH . $lib->lang . "/customer_menu.phtml";
?>

<section class="page-title-area">
    <div class="container">
        <div class="page-title-content">
            <h1><?= $item->name ?></h1>
            <ul>
                <li><a href="/shop">Magasin</a></li>
                <li><?= $item->name ?></li>
            </ul>
        </div>
    </div>
</section>


<section class="product-details-area ptb-70">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-md-12">
                <div class="products-details-image">
                    <div class="row">
                        <div class="col-lg-3 col-md-3">
                            <div class="owl-thumbs products-details-image-slides-owl-thumbs" data-slider-id="1">
                                <div class="owl-thumb-item">
                                    <?php
                                    if ($itemFeAImg['data'][0]->path) { ?>
                                        <img src="<?= $iniObj->imgPath . $itemFeAImg['data'][0]->path ?>" alt="image">
                                    <?php } else { ?>
                                        <img src="<?= $iniObj->UIPath ?>/img/products/products-img1.jpg" alt="image"></a>
                                    <?php  } ?>
                                </div>
                                <?php
                                if ($itemOthImgs['rows'] > 0) {
                                    foreach ($itemOthImgs['data'] as $key => $image) { ?>
                                        <div class="owl-thumb-item">
                                            <img src="<?= $iniObj->imgPath . $image->path ?>" alt="image">
                                        </div>
                                    <?php }
                                } else { ?>
                                    <div class="owl-thumb-item">
                                        <img src="<?= $iniObj->UIPath ?>/img/products/products-img1.jpg" alt="image">
                                    </div>
                                    <div class="owl-thumb-item">
                                        <img src="<?= $iniObj->UIPath ?>/img/products/products-img1.jpg" alt="image">
                                    </div>
                                <?php } ?>

                            </div>
                        </div>
                        <div class="col-lg-9 col-md-9">
                            <ul class="products-details-image-slides owl-theme owl-carousel" data-slider-id="1">
                                <li>
                                    <?php
                                    if ($itemFeAImg['data'][0]->path) { ?>
                                        <img src="<?= $iniObj->imgPath . $itemFeAImg['data'][0]->path ?>" alt="image">
                                    <?php } else { ?>
                                        <img src="<?= $iniObj->UIPath ?>/img/products/products-img1.jpg" alt="image"></a>
                                    <?php  } ?>
                                </li>
                                <?php
                                if ($itemOthImgs['rows'] > 0) {
                                    foreach ($itemOthImgs['data'] as $key => $image) { ?>
                                        <li>
                                            <img src="<?= $iniObj->imgPath . $image->path ?>" alt="image">
                                        </li>
                                    <?php }
                                } else { ?>
                                    <li>
                                        <img src="<?= $iniObj->UIPath ?>/img/products/products-img1.jpg" alt="image">
                                    </li>
                                    <li>
                                        <img src="<?= $iniObj->UIPath ?>/img/products/products-img1.jpg" alt="image">
                                    </li>
                                <?php } ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-md-12">
                <div class="products-details-desc">
                    <h3><?= $item->name ?></h3>
                    <div class="products-review">
                        <div class="rating">
                            <i class='bx bxs-star'></i>
                            <i class='bx bxs-star'></i>
                            <i class='bx bxs-star'></i>
                            <i class='bx bxs-star'></i>
                            <i class='bx bxs-star'></i>
                        </div>
                        <a href="products-details.html" class="rating-count">(3 reviews)</a>
                    </div>
                    <div class="price">
                        <span>€<?= $item->price_max ?></span>
                    </div>
                    <p><?= $item->description ?>.</p>
                    <div class="products-add-to-cart">
                        <!--<div class="quantities">
                            <span class="sub-title">Quantité:</span>
                            <div class="input-counter">
                                <span class="minus-btn"><i class='bx bx-minus'></i></span>
                                <input type="text" value="1" id="quantity">
                                <span class="plus-btn"><i class='bx bx-plus'></i></span>
                            </div>
                        </div>-->
                        <button type="button" id="<?= $item->item_id ?>" class="default-btn addcart"><i class="flaticon-trolley"></i> Ajouter au panier</button>
                    </div>
                    <ul class="social-share">
                        <li><span>Partager:</span></li>
                        <li><a href="#" target="#"><i class='bx bxl-facebook-square'></i></a></li>
                        <li><a href="#" target="#"><i class='bx bxl-twitter'></i></a></li>
                        <li><a href="#" target="#"><i class='bx bxl-instagram-alt'></i></a></li>
                        <li><a href="#" target="#"><i class='bx bxl-linkedin-square'></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-12 col-md-12">
                <div class="products-details-tabs">
                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                        <li class="nav-item"><a class="nav-link active" id="description-tab" data-toggle="tab" href="#description" role="tab" aria-controls="description">Specs</a></li>
                        <li class="nav-item"><a class="nav-link" id="shipping-tab" data-toggle="tab" href="#shipping" role="tab" aria-controls="shipping">Shipping</a></li>
                        <li class="nav-item"><a class="nav-link" id="reviews-tab" data-toggle="tab" href="#reviews" role="tab" aria-controls="reviews">Reviews (4)</a></li>
                    </ul>
                    <div class="tab-content" id="myTabContent">
                        <div class="tab-pane fade show active" id="description" role="tabpanel">
                            <h3><?= $item->name ?></h3>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea com modo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.</p>
                            <ul>
                                <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</li>
                                <li>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore fugiat nulla pariatur.</li>
                                <li>Excepteur sint occaecat cupidatat non proident.</li>
                            </ul>
                            <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. </p>
                        </div>
                        <div class="tab-pane fade" id="shipping" role="tabpanel">
                            <div class="table-responsive">
                                <table class="table table-bordered">
                                    <tbody>
                                        <tr>
                                            <td>Shipping</td>
                                            <td>This item Ship to USA</td>
                                        </tr>
                                        <tr>
                                            <td>Delivery</td>
                                            <td>
                                                Estimated between Wednesday 07/31/2021 and Monday 08/05/2021 <br>
                                                Will usually ship within 1 bussiness day.
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="reviews" role="tabpanel">
                            <div class="products-review-comments">
                                <h3>3 Reviews</h3>
                                <div class="user-review">
                                    <img src="<?= $iniObj->UIPath ?>/img/user1.jpg" alt="image">
                                    <div class="review-rating">
                                        <div class="review-stars">
                                            <i class='bx bxs-star checked'></i>
                                            <i class='bx bxs-star checked'></i>
                                            <i class='bx bxs-star checked'></i>
                                            <i class='bx bxs-star checked'></i>
                                            <i class='bx bxs-star checked'></i>
                                        </div>
                                    </div>
                                    <span class="d-block sub-comment">James Anderson</span>
                                    <p>Very well built theme, couldn't be happier with it. Can't wait for future updates to see what else they add in.</p>
                                </div>
                                <div class="user-review">
                                    <img src="<?= $iniObj->UIPath ?>/img/user2.jpg" alt="image">
                                    <div class="review-rating">
                                        <div class="review-stars">
                                            <i class='bx bxs-star checked'></i>
                                            <i class='bx bxs-star checked'></i>
                                            <i class='bx bxs-star checked'></i>
                                            <i class='bx bxs-star'></i>
                                            <i class='bx bxs-star'></i>
                                        </div>
                                    </div>
                                    <span class="d-block sub-comment">Sarah Taylor</span>
                                    <p>Was really easy to implement and they quickly answer my additional questions!</p>
                                </div>
                                <div class="user-review">
                                    <img src="<?= $iniObj->UIPath ?>/img/user3.jpg" alt="image">
                                    <div class="review-rating">
                                        <div class="review-stars">
                                            <i class='bx bxs-star checked'></i>
                                            <i class='bx bxs-star checked'></i>
                                            <i class='bx bxs-star checked'></i>
                                            <i class='bx bxs-star checked'></i>
                                            <i class='bx bxs-star checked'></i>
                                        </div>
                                    </div>
                                    <span class="d-block sub-comment">David Warner</span>
                                    <p>Stunning design, very dedicated crew who welcome new ideas suggested by customers, nice support.</p>
                                </div>
                                <div class="user-review">
                                    <img src="<?= $iniObj->UIPath ?>/img/user4.jpg" alt="image">
                                    <div class="review-rating">
                                        <div class="review-stars">
                                            <i class='bx bxs-star checked'></i>
                                            <i class='bx bxs-star checked'></i>
                                            <i class='bx bxs-star checked'></i>
                                            <i class='bx bxs-star checked'></i>
                                            <i class='bx bxs-star'></i>
                                        </div>
                                    </div>
                                    <span class="d-block sub-comment">King Kong</span>
                                    <p>Stunning design, very dedicated crew who welcome new ideas suggested by customers, nice support.</p>
                                </div>
                            </div>
                            <div class="review-form-wrapper">
                                <h3>Add a review</h3>
                                <p class="comment-notes">Your email address will not be published. Required fields are marked <span>*</span></p>
                                <form>
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12">
                                            <div class="rating">
                                                <input type="radio" id="star5" name="rating" value="5" /><label for="star5"></label>
                                                <input type="radio" id="star4" name="rating" value="4" /><label for="star4"></label>
                                                <input type="radio" id="star3" name="rating" value="3" /><label for="star3"></label>
                                                <input type="radio" id="star2" name="rating" value="2" /><label for="star2"></label>
                                                <input type="radio" id="star1" name="rating" value="1" /><label for="star1"></label>
                                            </div>
                                        </div>
                                        <div class="col-lg-6 col-md-6">
                                            <div class="form-group">
                                                <input type="text" class="form-control" placeholder="Name *">
                                            </div>
                                        </div>
                                        <div class="col-lg-6 col-md-6">
                                            <div class="form-group">
                                                <input type="email" class="form-control" placeholder="Email *">
                                            </div>
                                        </div>
                                        <div class="col-lg-12 col-md-12">
                                            <div class="form-group">
                                                <textarea placeholder="Your review" class="form-control" cols="30" rows="6"></textarea>
                                            </div>
                                        </div>
                                        <div class="col-lg-12 col-md-12">
                                            <p class="comment-form-cookies-consent">
                                                <input type="checkbox" id="test1">
                                                <label for="test1">Save my name, email, and website in this browser for the next time I comment.</label>
                                            </p>
                                        </div>
                                        <div class="col-lg-12 col-md-12">
                                            <button type="submit" class="default-btn">Submit</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<section class="products-area pb-40">
    <div class="container">
        <div class="section-title">
            <h2>Autres Articles</h2>
        </div>
        <div class="row">
            <?php foreach ($item_cat['data'] as $key => $item) : ?>
                <div class="col-xl-4 col-lg-6 col-md-4 col-sm-6">
                    <div class="single-products-box">
                        <div class="image">
                            <a href="/product_<?= $item->item_id ?>" class="d-block">
                                <?php
                                $itemImg = $sqlData->getItemFeaImg($item->item_id);
                                if ($itemImg['data'][0]->path) { ?>
                                    <img src="<?= $iniObj->imgPath . $itemImg['data'][0]->path ?>" alt="image">
                                <?php } else { ?>
                                    <img src="<?= $iniObj->UIPath ?>/img/products/products-img1.jpg" alt="image">
                                <?php  } ?>
                            </a>
                            <!-- <div class="new">New</div> -->
                            <ul class="buttons-list">
                                <li>
                                    <a href="javascript:void(0)" id="<?= $item->item_id ?>" class="addcart">
                                        <i class='bx bxs-cart-add'></i>
                                        <span class="tooltip-label">Ajouter au panier</span>
                                        <input type="hidden" value="1" id="quantity">
                                    </a>
                                </li>
                                <li>
                                    <a href="#" data-id="<?= $item->item_id ?>" class="quickview" onclick="loadItemdata(this.getAttribute('data-id'))" data-toggle="modal" data-target="">
                                        <i class='bx bx-search-alt'></i>
                                        <span class="tooltip-label">Voir</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="content">
                            <div class="rating">
                                <i class='bx bxs-star'></i>
                                <i class='bx bxs-star'></i>
                                <i class='bx bxs-star'></i>
                                <i class='bx bxs-star'></i>
                                <i class='bx bxs-star'></i>
                            </div>
                            <h3><a href="single.html"><?= $item->name ?></a></h3>
                            <div class="price">
                                <span class="new-price">$<?= $item->price_max ?></span>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</section>


<?php

include _VIEW_PATH . $lib->lang . "/customer_common_footer.phtml";
include _VIEW_PATH . "/customer_common_include_files.phtml";
?>