<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?= $iniObj->serviceName ?> | <?= $lang->trl('Reset Password') ?></title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/plugins/fontawesome-free/css/all.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/dist/css/adminlte.min.css">
    <!-- Toastr -->
    <link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/plugins/toastr/toastr.min.css">
    <!-- jQuery -->
    <script src="<?php echo $iniObj->UIPath; ?>/plugins/jquery/jquery.min.js"></script>
</head>

<body class="hold-transition login-page">

    <div class="login-box">
        <div class="login-logo">
            <a href="#"><b>CRM</b>JISCOMPUTING</a>
        </div>
        <!-- /.login-logo -->
        <div class="card">
            <div class="card-body login-card-body">
                <p class="login-box-msg"><?= $lang->trl('Enter your email to reset your password') ?></p>
                <!-- <form action="/login" method="post"> -->
                <form action="" method="" id="resetForm">
                    <div class="input-group mb-3">
                        <input type="email" id="email" name="email" class="form-control" placeholder="<?= $lang->trl('Email') ?>">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-envelope"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <!-- <div class="col-8">
                            <div class="icheck-primary">
                                <input type="checkbox" id="remember">
              <label for="remember">
                Remember Me
              </label>
                            </div>
                        </div> -->
                        <!-- /.col -->
                        <div class="col-6">
                            <button type="submit" id="sendbtn" class="btn btn-primary"><?= $lang->trl('Submit') ?></button>
                        </div>
                        <p class="mb-1">
                            <a href="<?= $iniObj->siteUrl ?>"><?= $lang->trl('Get back to login page') ?></a>
                        </p>
                        <!-- /.col -->
                    </div>
                </form>

                <!-- <div class="social-auth-links text-center mb-3">
        <p>- OR -</p>
        <a href="#" class="btn btn-block btn-primary">
          <i class="fab fa-facebook mr-2"></i> Sign in using Facebook
        </a>
        <a href="#" class="btn btn-block btn-danger">
          <i class="fab fa-google-plus mr-2"></i> Sign in using Google+
        </a>
      </div> -->
                <!-- /.social-auth-links -->

                <!-- <p class="mb-1">
                    <a href="/resetpass">I forgot my password</a>
                </p> -->

            </div>
            <!-- /.login-card-body -->
        </div>
    </div>

    <script>
        $("#sendbtn").on("click", function() {
            document.getElementById('sendbtn').innerHTML = "<?= $lang->trl('Submitting...') ?>   <i class='fa fa-spinner fa-spin'></i>";
            document.getElementById('sendbtn').disabled = true;
            var email = document.getElementById("email").value;
            // console.log(email)
            $.ajax({
                method: "POST",
                url: "/sendpass",
                data: {
                    email: email
                },
                success: function(msg) {
                    console.log(msg);
                    var val = msg.split("||");
                    if (val[0] == "false") {
                        toastr["error"](val[1]);
                        document.getElementById('sendbtn').innerHTML = "<?= $lang->trl('Submit') ?>";
                        document.getElementById('sendbtn').disabled = false;
                    } else if (val[0] == "true") {
                        toastr["success"](val[1]);
                        document.getElementById('sendbtn').innerHTML = "<?= $lang->trl('Submit') ?>";
                        document.getElementById('sendbtn').disabled = false;
                        $("#resetForm")[0].reset();
                    }
                }
            })

            return false;
        })
    </script>

    <?php //include _VIEW_PATH.$lib->lang."/common_footer.phtml";
    ?>

    <?php include _VIEW_PATH . "/common_include_files.phtml"; ?>

</body>