<?php

if ($iniObj->debugViews)
    echo __FILE__;
$title = "Boutique";
include _VIEW_PATH . "/customer_common_header.phtml";
?>
<?php

include _VIEW_PATH . "/customer_common_top_bar.phtml";
?>

<?php

include _VIEW_PATH . $lib->lang . "/customer_menu.phtml";
?>

<section class="order-tracking-area ptb-70">
    <div class="container">
        <div class="order-tracking-content">
            <form id="resetform">
                <div class="form-group">
                    <label>Votre mail</label>
                    <input type="email" id="useremail" name="useremail" class="form-control" placeholder="Email">
                </div>
                <button type="submit" id="mpresetbtn" class="default-btn">
                    <i class="fa fa-spinner fa-pulse" id="spinicon" style="display: none"></i>
                    <span id="btn-txt">Réinitialiser mot de passe</span>
                </button>
            </form>
        </div>
    </div>
</section>

<?php

include _VIEW_PATH . $lib->lang . "/customer_common_footer.phtml";
include _VIEW_PATH . "/customer_common_include_files.phtml";
?>

<script>
    $("#mpresetbtn").on("click", function() {
        var email = $("input[name='useremail']").val();
        $("#mpresetbtn").attr("disabled", true);
        document.getElementById("spinicon").style.display = "block";
        $("#btn-txt").text("Envoi en cours...");
        //console.log(email);
        $.ajax({
            method: "POST",
            url: "/sendpwd",
            data: {
                email
            },
            success: function(msg) {
                console.log(msg);
                var val = msg.split("||");
                if (val[0] == "true") {
                    $("#mpresetbtn").attr("disabled", false);
                    document.getElementById("spinicon").style.display = "none";
                    $("#btn-txt").text("Réinitialiser mot de passe");
                    $.notify(val[1], "success");
                    $("#loginModal").modal('show');
                    $('#resetform').each(function() {
                        this.reset();
                    });
                } else if (val[0] == "false") {
                    $("#mpresetbtn").attr("disabled", false);
                    document.getElementById("spinicon").style.display = "none";
                    $("#btn-txt").text("Réinitialiser mot de passe");
                    $.notify(val[1], "error");
                }
            }
        })
        return false;
    })
</script>