<?php
// if($iniObj->debugViews) echo __FILE__ ;
// $carouselActive = true;
// $title = "Articles neufs et occasions - Professionnel - Dépôt vente - Electroménager - Décoration - Informatique - Jeux vidéo - Son - Image - Téléphonie - Bricolage - Jardinage - Animalerie";
include _VIEW_PATH . "/common_header.phtml"; ?>

<?php
include _VIEW_PATH . "/customer/profile_left_menu.phtml";
include _VIEW_PATH . "common_top_bar.phtml";
// include _VIEW_PATH.$lib->lang."/top_menu.phtml";
?>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <!-- <h1>DataTables</h1> -->
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/customer/dashboard"><?= $lang->trl('Home') ?></a></li>
                        <li class="breadcrumb-item active"><?= $lang->trl('Missions') ?></li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title"><?= $lang->trl('Missions List') ?></h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <table id="example2" class="table table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th><?= $lang->trl('Label') ?></th>
                                        <th><?= $lang->trl('Company') ?></th>
                                        <th><?= $lang->trl('By who') ?></th>
                                        <th><?= $lang->trl('Contact') ?></th>
                                        <th><?= $lang->trl('Date') ?></th>
                                        <th><?= $lang->trl('status') ?></th>
                                        <th><?= $lang->trl('Action') ?></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($missions as $key => $mission) : ?>
                                        <tr>
                                            <td><?= $mission->type ?></td>
                                            <td><?= $mission->company ?></td>
                                            <td><?= ucfirst($mission->user_firstname) . ' ' . ucfirst($mission->user_lastname) ?></td>
                                            <td><?= ucfirst($mission->contact_firstname) . ' ' . ucfirst($mission->contact_lastname) ?></td>
                                            <td> <?= $sqlData->refomat_date($mission->mission_date, $format = 'full') ?></td>
                                            <td>
                                                <?php
                                                $current = date('Y/m/d H:i:s');
                                                if ($mission->status == 1 && strtotime($mission->mission_date) < strtotime($current)) {
                                                    echo '<span class="badge bg-danger">' . $lang->trl('not carried out') . ' (' . $lang->trl('expired date') . ')</span>';
                                                } else if ($mission->status == 1) {
                                                    echo '<span class="badge bg-danger">' . $lang->trl('not carried out') . '</span>';
                                                } else if ($mission->status == 2) {
                                                    echo '<span class="badge bg-success">' . $lang->trl('carried out') . '</span>';
                                                }
                                                ?>
                                            </td>
                                            <td><a class="btn btn-default btn-xs" title="Quick View" data-id="<?= $mission->mission_id ?>" onclick="loadModal($(this).attr('data-id'))"><i class="fas fa-eye"></i></a> <a class="btn btn-default btn-xs" href="/mission_<?= $mission->mission_id ?>" title="Open"><i class="fas fa-folder-open"></i></a></td>
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

<!-- Page specific script -->

<div class="modal fade" id="missiondetail">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Mission</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="details">
            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<script>
    function loadModal(id) {
        $.ajax({
            method: "POST",
            url: "/customer/loadmission",
            data: {
                id: id
            },
            success: function(msg) {
                //console.log(msg);
                $("#details").html(msg);
                $("#missiondetail").modal("show");
            }
        })
    }
</script>

<?php include _VIEW_PATH . $lib->lang . "/common_footer.phtml"; ?>
<?php include _VIEW_PATH . "/common_include_files.phtml"; ?>