<?php
if ($iniObj->debugViews)
    echo __FILE__;
$title = "Catégories || Tableau de bord || ".$iniObj->serviceName;
include _VIEW_PATH . '/dashboard_head.phtml';
include _VIEW_PATH . $lib->lang . '/dashboard_header.phtml';
include _VIEW_PATH . $lib->lang . '/dashboard_sidebar.phtml';
?>

<!-- ============================================================== -->
<!-- Start right Content here -->
<!-- ============================================================== -->
<div class="main-content">

    <div class="page-content">
        <div class="container-fluid">

            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box d-flex align-items-center justify-content-between">
                        <h4 class="mb-0 font-size-18">Categories
                            <small>
                                <button type="button" class="btn btn-primary waves-effect waves-light" data-toggle="modal" data-target="#addcategory">
                                    Nouvelle Catégorie
                                </button>
                            </small>
                        </h4>

                    </div>
                </div>
            </div>
            <!-- end page title -->

            <!-- Modal -->
            <div class="modal fade" id="addcategory" tabindex="-1" role="dialog" aria-labelledby="addcategory" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Nouvelle Catégorie</h5>
                            <button type="button" class="close waves-effect waves-light" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="form-group">
                                <label for="catname">Nom</label>
                                <input type="text" id="catname" class="form-control" placeholder="Entrer un nom">
                            </div>
                            <div class="form-group">
                                <label for="parent">Parent</label>
                                <select class="form-control" id="parent">
                                    <option>1</option>
                                    <option>2</option>
                                    <option>3</option>
                                    <option>4</option>
                                    <option>5</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="Description">Description</label>
                                <textarea class="form-control" id="Description" rows="3"></textarea>
                            </div>
                            <div>
                                <h4 class="card-title">Max File Size</h4>
                                <p class="card-subtitle mb-4">Example of dropify max file size.</p>

                                <input type="file" class="dropify" data-max-file-size="1M" />
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary waves-effect waves-light" data-dismiss="modal">Fermer</button>
                            <button type="submit" class="btn btn-primary waves-effect waves-light">Créer</button>
                        </div>
                    </div>
                </div>
            </div>


            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Liste des Catégories</h4>
                            <p class="card-subtitle mb-4">
                            </p>

                            <table id="basic-datatable" class="table dt-responsive nowrap">
                                <thead>
                                    <tr>
                                        <th>Catégories</th>
                                        <th>Nombre d'articles</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($categories as $key => $category) { 
                                            $items = $sqlData->countItemCat($category->category_id);
                                        ?>
                                        <tr>
                                            <td><?= $category->name ?></td>
                                            <td><?= $items['rows'] ?></td>
                                            <td><button type="button" title="Modifier" class="btn btn-primary waves-effect waves-light" data-toggle="modal" data-target="#editcategory">
                                                    <i class="fa fa-edit"></i>
                                                </button> <button data-toggle="modal" title="Spprimer" data-target="#editcategory" class="btn btn-danger"> <i class="fa fa-trash"></i></button></td>
                                        </tr>
                                    <?php } ?>
                                </tbody>
                            </table>

                        </div> <!-- end card body-->
                    </div> <!-- end card -->
                </div><!-- end col-->
            </div>
            <!-- end row-->



            <!-- Modal edit cat -->
            <div class="modal fade" id="editcategory" tabindex="-1" role="dialog" aria-labelledby="editcategory" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Modifier Catégorie</h5>
                            <button type="button" class="close waves-effect waves-light" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="form-group">
                                <label for="catname">Nom</label>
                                <input type="text" id="catname" class="form-control" placeholder="Entrer un nom">
                            </div>
                            <div class="form-group">
                                <label for="parent">Parent</label>
                                <select class="form-control" id="parent">
                                    <option>1</option>
                                    <option>2</option>
                                    <option>3</option>
                                    <option>4</option>
                                    <option>5</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="Description">Description</label>
                                <textarea class="form-control" id="Description" rows="3"></textarea>
                            </div>
                            <div>
                                <h4 class="card-title">Max File Size</h4>
                                <p class="card-subtitle mb-4">Example of dropify max file size.</p>

                                <input type="file" class="dropify" data-max-file-size="1M" />
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary waves-effect waves-light" data-dismiss="modal">Fermer</button>
                            <button type="submit" class="btn btn-primary waves-effect waves-light">Créer</button>
                        </div>
                    </div>
                </div>
            </div>



        </div> <!-- container-fluid -->
    </div>
    <!-- End Page-content -->

    <?php
    include _VIEW_PATH . $lib->lang . '/dashboard_footer.phtml';
    include _VIEW_PATH . 'dashboard_include_files.phtml';
    ?>