<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1><?= $lang->trl('Add a company') ?></h1>
        </div>
        <!-- <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">Ajouter une societe</li>
          </ol>
        </div> -->
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <!-- left column -->
        <div class="col-md-8">
          <!-- general form elements -->
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title"><?= $lang->trl('Add a company') ?></h3>
            </div>
            <header class="text-center mb-4">
              <div class="text-danger">
                <h6 id="error_message"></h6>
              </div>
              <div class="text-success">
                <h6 id="success_message"></h6>
              </div>
            </header>
            <!-- /.card-header -->
            <!-- form start -->
            <form id="company_form">
              <div class="card-body">
                <div class="form-group">
                  <label for="company_name"><?= $lang->trl('Company name') ?></label>
                  <input type="text" name="company_name" class="form-control" id="company_name" placeholder="<?= $lang->trl('Company name') ?>" onkeypress="return (event.charCode > 64 && event.charCode < 91) || (event.charCode > 96 && event.charCode < 123) || (event.charCode == 45) || (event.charCode==32)">
                </div>
                <div class="form-group">
                  <label for="company_zipcode"><?= $lang->trl('Company zipcode') ?></label>
                  <input type="number" name="company_zipcode" class="form-control" id="company_zipcode" placeholder="<?= $lang->trl('Company zipcode') ?>">
                </div>
                <div class="form-group">
                  <label for="company_city"><?= $lang->trl('Company Address') ?></label>
                  <input type="text" name="company_adress" class="form-control" id="company_adress" placeholder="<?= $lang->trl('Company Address') ?>">
                </div>
                <div class="form-group">
                  <label for="company_city"><?= $lang->trl('Company city') ?></label>
                  <input type="text" name="company_city" class="form-control" id="company_city" placeholder="<?= $lang->trl('Company city') ?>" onkeypress="return (event.charCode > 64 && event.charCode < 91) || (event.charCode > 96 && event.charCode < 123) || (event.charCode==32)">
                </div>
                <div class="form-group">
                  <label for="company_country"><?= $lang->trl('Company Country') ?></label>
                  <!-- <input type="text" name="company_country" class="form-control" id="company_country" placeholder="<?= $lang->trl('Company city') ?>"> -->
                  <select class="form-control" id="company_country" name="pays">
                    <option value=""> -- <?= $lang->trl('Choose a country') ?> -- </option>
                    <option value="France">France </option>
                    <option value="Afghanistan">Afghanistan </option>
                    <option value="Afrique_Centrale">Afrique_Centrale </option>
                    <option value="Afrique_du_sud">Afrique_du_Sud </option>
                    <option value="Albanie">Albanie </option>
                    <option value="Algerie">Algerie </option>
                    <option value="Allemagne">Allemagne </option>
                    <option value="Andorre">Andorre </option>
                    <option value="Angola">Angola </option>
                    <option value="Anguilla">Anguilla </option>
                    <option value="Arabie_Saoudite">Arabie_Saoudite </option>
                    <option value="Argentine">Argentine </option>
                    <option value="Armenie">Armenie </option>
                    <option value="Australie">Australie </option>
                    <option value="Autriche">Autriche </option>
                    <option value="Azerbaidjan">Azerbaidjan </option>

                    <option value="Bahamas">Bahamas </option>
                    <option value="Bangladesh">Bangladesh </option>
                    <option value="Barbade">Barbade </option>
                    <option value="Bahrein">Bahrein </option>
                    <option value="Belgique">Belgique </option>
                    <option value="Belize">Belize </option>
                    <option value="Benin">Benin </option>
                    <option value="Bermudes">Bermudes </option>
                    <option value="Bielorussie">Bielorussie </option>
                    <option value="Bolivie">Bolivie </option>
                    <option value="Botswana">Botswana </option>
                    <option value="Bhoutan">Bhoutan </option>
                    <option value="Boznie_Herzegovine">Boznie_Herzegovine </option>
                    <option value="Bresil">Bresil </option>
                    <option value="Brunei">Brunei </option>
                    <option value="Bulgarie">Bulgarie </option>
                    <option value="Burkina_Faso">Burkina_Faso </option>
                    <option value="Burundi">Burundi </option>

                    <option value="Caiman">Caiman </option>
                    <option value="Cambodge">Cambodge </option>
                    <option value="Cameroun">Cameroun </option>
                    <option value="Canada">Canada </option>
                    <option value="Canaries">Canaries </option>
                    <option value="Cap_vert">Cap_Vert </option>
                    <option value="Chili">Chili </option>
                    <option value="Chine">Chine </option>
                    <option value="Chypre">Chypre </option>
                    <option value="Colombie">Colombie </option>
                    <option value="Comores">Colombie </option>
                    <option value="Congo">Congo </option>
                    <option value="Congo_democratique">Congo_democratique </option>
                    <option value="Cook">Cook </option>
                    <option value="Coree_du_Nord">Coree_du_Nord </option>
                    <option value="Coree_du_Sud">Coree_du_Sud </option>
                    <option value="Costa_Rica">Costa_Rica </option>
                    <option value="Cote_d_Ivoire">Côte_d_Ivoire </option>
                    <option value="Croatie">Croatie </option>
                    <option value="Cuba">Cuba </option>

                    <option value="Danemark">Danemark </option>
                    <option value="Djibouti">Djibouti </option>
                    <option value="Dominique">Dominique </option>

                    <option value="Egypte">Egypte </option>
                    <option value="Emirats_Arabes_Unis">Emirats_Arabes_Unis </option>
                    <option value="Equateur">Equateur </option>
                    <option value="Erythree">Erythree </option>
                    <option value="Espagne">Espagne </option>
                    <option value="Estonie">Estonie </option>
                    <option value="Etats_Unis">Etats_Unis </option>
                    <option value="Ethiopie">Ethiopie </option>

                    <option value="Falkland">Falkland </option>
                    <option value="Feroe">Feroe </option>
                    <option value="Fidji">Fidji </option>
                    <option value="Finlande">Finlande </option>
                    <option value="France">France </option>

                    <option value="Gabon">Gabon </option>
                    <option value="Gambie">Gambie </option>
                    <option value="Georgie">Georgie </option>
                    <option value="Ghana">Ghana </option>
                    <option value="Gibraltar">Gibraltar </option>
                    <option value="Grece">Grece </option>
                    <option value="Grenade">Grenade </option>
                    <option value="Groenland">Groenland </option>
                    <option value="Guadeloupe">Guadeloupe </option>
                    <option value="Guam">Guam </option>
                    <option value="Guatemala">Guatemala</option>
                    <option value="Guernesey">Guernesey </option>
                    <option value="Guinee">Guinee </option>
                    <option value="Guinee_Bissau">Guinee_Bissau </option>
                    <option value="Guinee equatoriale">Guinee_Equatoriale </option>
                    <option value="Guyana">Guyana </option>
                    <option value="Guyane_Francaise ">Guyane_Francaise </option>

                    <option value="Haiti">Haiti </option>
                    <option value="Hawaii">Hawaii </option>
                    <option value="Honduras">Honduras </option>
                    <option value="Hong_Kong">Hong_Kong </option>
                    <option value="Hongrie">Hongrie </option>

                    <option value="Inde">Inde </option>
                    <option value="Indonesie">Indonesie </option>
                    <option value="Iran">Iran </option>
                    <option value="Iraq">Iraq </option>
                    <option value="Irlande">Irlande </option>
                    <option value="Islande">Islande </option>
                    <option value="Israel">Israel </option>
                    <option value="Italie">italie </option>

                    <option value="Jamaique">Jamaique </option>
                    <option value="Jan Mayen">Jan Mayen </option>
                    <option value="Japon">Japon </option>
                    <option value="Jersey">Jersey </option>
                    <option value="Jordanie">Jordanie </option>

                    <option value="Kazakhstan">Kazakhstan </option>
                    <option value="Kenya">Kenya </option>
                    <option value="Kirghizstan">Kirghizistan </option>
                    <option value="Kiribati">Kiribati </option>
                    <option value="Koweit">Koweit </option>

                    <option value="Laos">Laos </option>
                    <option value="Lesotho">Lesotho </option>
                    <option value="Lettonie">Lettonie </option>
                    <option value="Liban">Liban </option>
                    <option value="Liberia">Liberia </option>
                    <option value="Liechtenstein">Liechtenstein </option>
                    <option value="Lituanie">Lituanie </option>
                    <option value="Luxembourg">Luxembourg </option>
                    <option value="Lybie">Lybie </option>

                    <option value="Macao">Macao </option>
                    <option value="Macedoine">Macedoine </option>
                    <option value="Madagascar">Madagascar </option>
                    <option value="Madère">Madère </option>
                    <option value="Malaisie">Malaisie </option>
                    <option value="Malawi">Malawi </option>
                    <option value="Maldives">Maldives </option>
                    <option value="Mali">Mali </option>
                    <option value="Malte">Malte </option>
                    <option value="Man">Man </option>
                    <option value="Mariannes du Nord">Mariannes du Nord </option>
                    <option value="Maroc">Maroc </option>
                    <option value="Marshall">Marshall </option>
                    <option value="Martinique">Martinique </option>
                    <option value="Maurice">Maurice </option>
                    <option value="Mauritanie">Mauritanie </option>
                    <option value="Mayotte">Mayotte </option>
                    <option value="Mexique">Mexique </option>
                    <option value="Micronesie">Micronesie </option>
                    <option value="Midway">Midway </option>
                    <option value="Moldavie">Moldavie </option>
                    <option value="Monaco">Monaco </option>
                    <option value="Mongolie">Mongolie </option>
                    <option value="Montserrat">Montserrat </option>
                    <option value="Mozambique">Mozambique </option>

                    <option value="Namibie">Namibie </option>
                    <option value="Nauru">Nauru </option>
                    <option value="Nepal">Nepal </option>
                    <option value="Nicaragua">Nicaragua </option>
                    <option value="Niger">Niger </option>
                    <option value="Nigeria">Nigeria </option>
                    <option value="Niue">Niue </option>
                    <option value="Norfolk">Norfolk </option>
                    <option value="Norvege">Norvege </option>
                    <option value="Nouvelle_Caledonie">Nouvelle_Caledonie </option>
                    <option value="Nouvelle_Zelande">Nouvelle_Zelande </option>

                    <option value="Oman">Oman </option>
                    <option value="Ouganda">Ouganda </option>
                    <option value="Ouzbekistan">Ouzbekistan </option>

                    <option value="Pakistan">Pakistan </option>
                    <option value="Palau">Palau </option>
                    <option value="Palestine">Palestine </option>
                    <option value="Panama">Panama </option>
                    <option value="Papouasie_Nouvelle_Guinee">Papouasie_Nouvelle_Guinee </option>
                    <option value="Paraguay">Paraguay </option>
                    <option value="Pays_Bas">Pays_Bas </option>
                    <option value="Perou">Perou </option>
                    <option value="Philippines">Philippines </option>
                    <option value="Pologne">Pologne </option>
                    <option value="Polynesie">Polynesie </option>
                    <option value="Porto_Rico">Porto_Rico </option>
                    <option value="Portugal">Portugal </option>

                    <option value="Qatar">Qatar </option>

                    <option value="Republique_Dominicaine">Republique_Dominicaine </option>
                    <option value="Republique_Tcheque">Republique_Tcheque </option>
                    <option value="Reunion">Reunion </option>
                    <option value="Roumanie">Roumanie </option>
                    <option value="Royaume_Uni">Royaume_Uni </option>
                    <option value="Russie">Russie </option>
                    <option value="Rwanda">Rwanda </option>

                    <option value="Sahara Occidental">Sahara Occidental </option>
                    <option value="Sainte_Lucie">Sainte_Lucie </option>
                    <option value="Saint_Marin">Saint_Marin </option>
                    <option value="Salomon">Salomon </option>
                    <option value="Salvador">Salvador </option>
                    <option value="Samoa_Occidentales">Samoa_Occidentales</option>
                    <option value="Samoa_Americaine">Samoa_Americaine </option>
                    <option value="Sao_Tome_et_Principe">Sao_Tome_et_Principe </option>
                    <option value="Senegal">Senegal </option>
                    <option value="Seychelles">Seychelles </option>
                    <option value="Sierra Leone">Sierra Leone </option>
                    <option value="Singapour">Singapour </option>
                    <option value="Slovaquie">Slovaquie </option>
                    <option value="Slovenie">Slovenie</option>
                    <option value="Somalie">Somalie </option>
                    <option value="Soudan">Soudan </option>
                    <option value="Sri_Lanka">Sri_Lanka </option>
                    <option value="Suede">Suede </option>
                    <option value="Suisse">Suisse </option>
                    <option value="Surinam">Surinam </option>
                    <option value="Swaziland">Swaziland </option>
                    <option value="Syrie">Syrie </option>

                    <option value="Tadjikistan">Tadjikistan </option>
                    <option value="Taiwan">Taiwan </option>
                    <option value="Tonga">Tonga </option>
                    <option value="Tanzanie">Tanzanie </option>
                    <option value="Tchad">Tchad </option>
                    <option value="Thailande">Thailande </option>
                    <option value="Tibet">Tibet </option>
                    <option value="Timor_Oriental">Timor_Oriental </option>
                    <option value="Togo">Togo </option>
                    <option value="Trinite_et_Tobago">Trinite_et_Tobago </option>
                    <option value="Tristan da cunha">Tristan de cuncha </option>
                    <option value="Tunisie">Tunisie </option>
                    <option value="Turkmenistan">Turmenistan </option>
                    <option value="Turquie">Turquie </option>

                    <option value="Ukraine">Ukraine </option>
                    <option value="Uruguay">Uruguay </option>

                    <option value="Vanuatu">Vanuatu </option>
                    <option value="Vatican">Vatican </option>
                    <option value="Venezuela">Venezuela </option>
                    <option value="Vierges_Americaines">Vierges_Americaines </option>
                    <option value="Vierges_Britanniques">Vierges_Britanniques </option>
                    <option value="Vietnam">Vietnam </option>

                    <option value="Wake">Wake </option>
                    <option value="Wallis et Futuma">Wallis et Futuma </option>

                    <option value="Yemen">Yemen </option>
                    <option value="Yougoslavie">Yougoslavie </option>

                    <option value="Zambie">Zambie </option>
                    <option value="Zimbabwe">Zimbabwe </option>

                  </select>
                </div>
                <div class="form-group">
                  <label for="activity_area"><?= $lang->trl('Field of activity') ?></label>
                  <input type="text" name="activity_area" class="form-control" id="activity_area" placeholder="<?= $lang->trl('Field of activity') ?>" onkeypress="return (event.charCode > 64 && event.charCode < 91) || (event.charCode > 96 && event.charCode < 123) || (event.charCode==32)">
                </div>
                <div class="form-group">
                  <label for="company_type"><?= $lang->trl('Company type') ?></label>
                  <select class="form-control" name="company_type" id="company_type">
                    <option value=""> --<?= $lang->trl('Choose a type') ?>-- </option>
                    <option value="public"><?= $lang->trl('Public') ?></option>
                    <option value="private"><?= $lang->trl('Private') ?></option>
                  </select>
                </div>
                <div class="form-group">
                  <label for="code_naf"><?= $lang->trl('Code NAF') ?></label>
                  <input type="text" name="code_naf" class="form-control pull-right" id="code_naf">
                </div>
                <div class="form-group">
                  <label for="web_site"><?= $lang->trl('Web Site') ?></label>
                  <input type="url" name="web_site" placeholder="Ex : https://www.siteweb.com/" class="form-control pull-right" id="web_site">
                </div>
                <!-- </div> -->
                <!-- <div class="form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">Check me out</label>
              </div> -->
              </div>
              <!-- /.card-body -->

              <div class="card-footer">
                <button type="button" id="submit_company" class="btn btn-primary pull-right"><?= $lang->trl('Submit') ?></button>
              </div>
            </form>
          </div>
          <!-- /.card -->


        </div>

        <div class="col-md-4">
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title"><?= $lang->trl('Add a company') ?></h3>
            </div>
            <form id="uploadcsv" enctype="multipart/form-data">
              <!-- <input type="hidden" name="is_csv" /> -->
              <div class="card-body">
                <div class="form-group">
                  <label for="company_csv"><?= $lang->trl('Import a XLSX/XLX file') ?></label>
                  <input type="file" name="company_csv" class="form-control" id="company_csv" accept=".xlsx, .xls, .csv" /><br>
                  <button class="btn btn-success btn-sm" type="button" onclick="uploadCSV()" name="importcsv" id="importcsv"><?= $lang->trl('Save') ?></button>
                </div>
              </div>
            </form>
          </div>
          <!--/.col (left) -->
          <!-- right column -->

          <!--/.col (right) -->
        </div>
        <!-- /.row -->
        <!--/.col (left) -->
        <!-- right column -->
        <!-- <div class="col-md-6"> -->
        <!-- Form Element sizes -->
        <!-- <div class="card card-success">
              <div class="card-header">
                <h3 class="card-title">Different Height</h3>
              </div>
              <div class="card-body">
                <input class="form-control form-control-lg" type="text" placeholder=".form-control-lg">
                <br>
                <input class="form-control" type="text" placeholder="Default input">
                <br>
                <input class="form-control form-control-sm" type="text" placeholder=".form-control-sm">
              </div> -->
        <!-- /.card-body -->
        <!-- </div> -->
        <!-- /.card -->


        <!-- /.card -->
        <!-- </div> -->
        <!--/.col (right) -->
      </div>
      <!-- /.row -->
      <!-- </div> -->
      <!-- /.container-fluid -->
  </section>
  <!-- /.content -->
</div>
<!-- /.content-wrapper -->

<script>
  $('#submit_company').click(function() {
    saveCompany();
  })

  function saveCompany() {
    document.getElementById('submit_company').innerHTML = "<?= $lang->trl('Saving company, please wait...') ?>  <i class='fa fa-spinner fa-spin'></i>";


    var company_name = encodeURIComponent($("#company_name").val());
    var company_zipcode = encodeURIComponent($("#company_zipcode").val());
    var company_city = encodeURIComponent($("#company_city").val());
    var company_country = encodeURIComponent($("#company_country").val());
    var company_adress = encodeURIComponent($("#company_adress").val());
    var activity_area = encodeURIComponent($("#activity_area").val());
    var company_type = encodeURIComponent($("#company_type").val());
    var code_naf = encodeURIComponent($("#code_naf").val());
    var web_site = encodeURIComponent($("#web_site").val());

    // alert(code_naf)
    $.ajax({
      url: '/customer/saveNewCompany/',
      type: 'POST',
      data: {
        company_name: company_name,
        company_zipcode: company_zipcode,
        company_city: company_city,
        company_adress: company_adress,
        company_country: company_country,
        activity_area: activity_area,
        company_type: company_type,
        code_naf: code_naf,
        web_site : web_site
      },

      success: function(msg) {
        var val = msg.split('||');
        console.log(msg);
        if (val[0] == "false") {
          $("#error_message").html(val[1]);
          $("#error_message").show();
          $("#submit_company").attr("disabled", false);
          $("#submit_company").html("Enregistrer");

        } else if (val[0] == "true") {
          $("#success_message").html(val[1]);
          $("#error_message").html("");
          $("#success_message").show();
          $("#submit_company").html(val[1]).attr("disabled", true);

          rnd = Math.random();
          window.location.href = '/customer/companies/' + rnd;


        }

      },
      error: function(resultat, statut, erreur) {
        $("#error_message").html("<?= $lang->trl('Error, please try again') ?> <i class='fa fa-stop-circle'></i>");
        console.log('Resultat : ' + resultat);
        console.log('Statut : ' + statut);
        console.log('Erreur : ' + erreur);
      }
    });

  }


  function uploadCSV() {
    var form = $("#uploadcsv")[0];
    var formData = new FormData(form);
    $.ajax({
      url: "/customer/CompanyCSV/",
      type: "POST",
      enctype: 'multipart/form-data',
      data: formData,
      processData: false,
      contentType: false,
      cache: false,
      timeout: 600000,
      success: function(msg) {
        console.log(msg);
        var val = msg.split("||");
        if (val[0] == "true") {
          toastr["success"](val[1]);
          // location.reload();
          window.location.href = "/customer/company_list";
        } else if (val[0] == "false") {
          toastr["error"](val[1]);
        }
      }
    })
  }
</script>
</script>