 <!-- Content Wrapper. Contains page content -->
 <div class="content-wrapper">
     <!-- Content Header (Page header) -->
     <section class="content-header">
         <div class="container-fluid">
             <div class="row mb-2">
                 <div class="col-sm-6">
                     <h1><?= $company_data->company_name ?></h1>
                 </div>
                 <div class="col-sm-6">
                     <ol class="breadcrumb float-sm-right">
                         <li class="breadcrumb-item"><a href="/customer/company_list"><?= $lang->trl('Company') ?></a></li>
                         <li class="breadcrumb-item active"><?= $company_data->company_name ?></li>
                     </ol>
                 </div>
             </div>
         </div><!-- /.container-fluid -->
     </section>

     <section class="content">
         <div class="container-fluid">
             <div class="row">
                 <div class="col-12">
                     <div class="invoice p-3 mb-3">
                         <!-- title row -->
                         <div class="row">
                             <div class="col-12">
                                 <h4>
                                     <i class="fas fa-globe"></i> <?= $company_data->company_name ?>.
                                     <!-- <small class="float-right">Date: 2/10/2014</small> -->
                                 </h4>
                             </div>
                             <!-- /.col -->
                         </div>
                         <!-- info row -->
                         <div class="row invoice-info">
                             <div class="col-sm-4 invoice-col">
                                 <!-- From -->
                                 <address>
                                     <strong><?= $company_data->company_name ?>.</strong><br>
                                     <?= $company_data->adress ?><br>
                                     <?= $company_data->city . ', ' . $company_data->country ?><br>
                                     <!-- Phone: (804) 123-5432<br>
                                     Email: info@almasaeedstudio.com -->
                                 </address>
                             </div>
                             <!-- /.col -->
                             <!-- <div class="col-sm-4 invoice-col">
                                 To
                                 <address>
                                     <strong>John Doe</strong><br>
                                     795 Folsom Ave, Suite 600<br>
                                     San Francisco, CA 94107<br>
                                     Phone: (555) 539-1037<br>
                                     Email: john.doe@example.com
                                 </address>
                             </div> -->
                             <!-- /.col -->
                             <!-- <div class="col-sm-4 invoice-col">
                                 <b>Invoice #007612</b><br>
                                 <br>
                                 <b>Order ID:</b> 4F3S8J<br>
                                 <b>Payment Due:</b> 2/22/2014<br>
                                 <b>Account:</b> 968-34567
                             </div> -->
                             <!-- /.col -->
                         </div>

                     </div>
                     <!-- /.invoice -->
                 </div><!-- /.col -->
             </div><!-- /.row -->

             <div class="row">
                 <div class="col-md-3">

                     <!-- Profile Image -->
                     <div class="card card-primary card-outline">
                         <div class="card-body box-profile">

                             <h3 class="profile-username text-center"><?= $company_data->company_name ?></h3>

                             <p class="text-muted text-center"><?= $company_data->activity_area ?></p>
                         </div>
                         <!-- /.card-body -->
                     </div>
                     <!-- /.card -->

                     <!-- About Me Box -->
                     <div class="card card-primary">
                         <!-- <div class="card-header">
                             <h3 class="card-title">About Me</h3>
                         </div> -->
                         <!-- /.card-header -->
                         <div class="card-body">

                             <strong><i class="fas fa-map-marker-alt mr-1"></i> <?= $lang->trl('Address') ?></strong>

                             <p class="text-muted"><?= $company_data->adress . ', ' . $company_data->postal . ', ' . $company_data->city . ', ' . $company_data->country ?></p>

                             <hr>

                             <strong><i class="fas fa-pencil-alt mr-1"></i> <?= $lang->trl('Web Site') ?></strong>

                             <p class="text-muted">
                                 <span class="tag tag-danger"><?= ($company_data->website) ? $company_data->website : $lang->trl('No Web Site') ?></span>
                             </p>

                             <!-- <hr>

                             <strong><i class="far fa-file-alt mr-1"></i> Notes</strong>

                             <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum enim neque.</p> -->
                         </div>
                         <!-- /.card-body -->
                     </div>
                     <!-- /.card -->
                 </div>
                 <!-- /.col -->
                 <div class="col-md-9">
                     <div class="card">
                         <div class="card-header p-2">
                             <ul class="nav nav-pills">
                                 <!-- <li class="nav-item"><a class="nav-link active" href="#activity" data-toggle="tab">Activity</a></li>
                                 <li class="nav-item"><a class="nav-link" href="#timeline" data-toggle="tab">Timeline</a></li>
                                 <li class="nav-item"><a class="nav-link active" href="#comments" data-toggle="tab"><?= $lang->trl('Comment') ?></a></li> -->
                             </ul>
                         </div><!-- /.card-header -->
                         <div class="card-body">
                             <div class="tab-content">
                                 <!-- <div class="tab-pane" id="activity">
                                     <div class="post">
                                         <div class="user-block">
                                             <img class="img-circle img-bordered-sm" src="../../dist/img/user1-128x128.jpg" alt="user image">
                                             <span class="username">
                                                 <a href="#">Jonathan Burke Jr.</a>
                                                 <a href="#" class="float-right btn-tool"><i class="fas fa-times"></i></a>
                                             </span>
                                             <span class="description">Shared publicly - 7:30 PM today</span>
                                         </div>
                                         <p>
                                             Lorem ipsum represents a long-held tradition for designers,
                                             typographers and the like. Some people hate it and argue for
                                             its demise, but others ignore the hate as they create awesome
                                             tools to help create filler text for everyone from bacon lovers
                                             to Charlie Sheen fans.
                                         </p>

                                         <p>
                                             <a href="#" class="link-black text-sm mr-2"><i class="fas fa-share mr-1"></i> Share</a>
                                             <a href="#" class="link-black text-sm"><i class="far fa-thumbs-up mr-1"></i> Like</a>
                                             <span class="float-right">
                                                 <a href="#" class="link-black text-sm">
                                                     <i class="far fa-comments mr-1"></i> Comments (5)
                                                 </a>
                                             </span>
                                         </p>

                                         <input class="form-control form-control-sm" type="text" placeholder="Type a comment">
                                     </div>

                                     <div class="post clearfix">
                                         <div class="user-block">
                                             <img class="img-circle img-bordered-sm" src="../../dist/img/user7-128x128.jpg" alt="User Image">
                                             <span class="username">
                                                 <a href="#">Sarah Ross</a>
                                                 <a href="#" class="float-right btn-tool"><i class="fas fa-times"></i></a>
                                             </span>
                                             <span class="description">Sent you a message - 3 days ago</span>
                                         </div>
                                         <p>
                                             Lorem ipsum represents a long-held tradition for designers,
                                             typographers and the like. Some people hate it and argue for
                                             its demise, but others ignore the hate as they create awesome
                                             tools to help create filler text for everyone from bacon lovers
                                             to Charlie Sheen fans.
                                         </p>

                                         <form class="form-horizontal">
                                             <div class="input-group input-group-sm mb-0">
                                                 <input class="form-control form-control-sm" placeholder="Response">
                                                 <div class="input-group-append">
                                                     <button type="submit" class="btn btn-danger">Send</button>
                                                 </div>
                                             </div>
                                         </form>
                                     </div>
                                     <div class="post">
                                         <div class="user-block">
                                             <img class="img-circle img-bordered-sm" src="../../dist/img/user6-128x128.jpg" alt="User Image">
                                             <span class="username">
                                                 <a href="#">Adam Jones</a>
                                                 <a href="#" class="float-right btn-tool"><i class="fas fa-times"></i></a>
                                             </span>
                                             <span class="description">Posted 5 photos - 5 days ago</span>
                                         </div>
                                         <div class="row mb-3">
                                             <div class="col-sm-6">
                                                 <img class="img-fluid" src="../../dist/img/photo1.png" alt="Photo">
                                             </div>
                                             <div class="col-sm-6">
                                                 <div class="row">
                                                     <div class="col-sm-6">
                                                         <img class="img-fluid mb-3" src="../../dist/img/photo2.png" alt="Photo">
                                                         <img class="img-fluid" src="../../dist/img/photo3.jpg" alt="Photo">
                                                     </div>
                                                     <div class="col-sm-6">
                                                         <img class="img-fluid mb-3" src="../../dist/img/photo4.jpg" alt="Photo">
                                                         <img class="img-fluid" src="../../dist/img/photo1.png" alt="Photo">
                                                     </div>
                                                 </div>
                                             </div>
                                         </div>

                                         <p>
                                             <a href="#" class="link-black text-sm mr-2"><i class="fas fa-share mr-1"></i> Share</a>
                                             <a href="#" class="link-black text-sm"><i class="far fa-thumbs-up mr-1"></i> Like</a>
                                             <span class="float-right">
                                                 <a href="#" class="link-black text-sm">
                                                     <i class="far fa-comments mr-1"></i> Comments (5)
                                                 </a>
                                             </span>
                                         </p>

                                         <input class="form-control form-control-sm" type="text" placeholder="Type a comment">
                                     </div>
                                 </div> -->
                                 <!-- /.tab-pane -->
                                 <!-- <div class="tab-pane" id="timeline">
                                     <div class="timeline timeline-inverse">
                                         <div class="time-label">
                                             <span class="bg-danger">
                                                 10 Feb. 2014
                                             </span>
                                         </div>
                                         <div>
                                             <i class="fas fa-envelope bg-primary"></i>

                                             <div class="timeline-item">
                                                 <span class="time"><i class="far fa-clock"></i> 12:05</span>

                                                 <h3 class="timeline-header"><a href="#">Support Team</a> sent you an email</h3>

                                                 <div class="timeline-body">
                                                     Etsy doostang zoodles disqus groupon greplin oooj voxy zoodles,
                                                     weebly ning heekya handango imeem plugg dopplr jibjab, movity
                                                     jajah plickers sifteo edmodo ifttt zimbra. Babblely odeo kaboodle
                                                     quora plaxo ideeli hulu weebly balihoo...
                                                 </div>
                                                 <div class="timeline-footer">
                                                     <a href="#" class="btn btn-primary btn-sm">Read more</a>
                                                     <a href="#" class="btn btn-danger btn-sm">Delete</a>
                                                 </div>
                                             </div>
                                         </div>
                                         <div>
                                             <i class="fas fa-user bg-info"></i>

                                             <div class="timeline-item">
                                                 <span class="time"><i class="far fa-clock"></i> 5 mins ago</span>

                                                 <h3 class="timeline-header border-0"><a href="#">Sarah Young</a> accepted your friend request
                                                 </h3>
                                             </div>
                                         </div>
                                         <div>
                                             <i class="fas fa-comments bg-warning"></i>

                                             <div class="timeline-item">
                                                 <span class="time"><i class="far fa-clock"></i> 27 mins ago</span>

                                                 <h3 class="timeline-header"><a href="#">Jay White</a> commented on your post</h3>

                                                 <div class="timeline-body">
                                                     Take me to your leader!
                                                     Switzerland is small and neutral!
                                                     We are more like Germany, ambitious and misunderstood!
                                                 </div>
                                                 <div class="timeline-footer">
                                                     <a href="#" class="btn btn-warning btn-flat btn-sm">View comment</a>
                                                 </div>
                                             </div>
                                         </div>
                                         <div class="time-label">
                                             <span class="bg-success">
                                                 3 Jan. 2014
                                             </span>
                                         </div>
                                         <div>
                                             <i class="fas fa-camera bg-purple"></i>

                                             <div class="timeline-item">
                                                 <span class="time"><i class="far fa-clock"></i> 2 days ago</span>

                                                 <h3 class="timeline-header"><a href="#">Mina Lee</a> uploaded new photos</h3>

                                                 <div class="timeline-body">
                                                     <img src="https://placehold.it/150x100" alt="...">
                                                     <img src="https://placehold.it/150x100" alt="...">
                                                     <img src="https://placehold.it/150x100" alt="...">
                                                     <img src="https://placehold.it/150x100" alt="...">
                                                 </div>
                                             </div>
                                         </div>
                                         <div>
                                             <i class="far fa-clock bg-gray"></i>
                                         </div>
                                     </div>
                                 </div> -->
                                 <!-- /.tab-pane -->

                                 <div class="active tab-pane" id="comments">
                                     <div class="col-6">
                                         <h4><?= $lang->trl('Recent Comments') ?></h4>
                                         <div style=" height: 400px; overflow: auto;" id="comment" data-id="<?= $company_data->company_id ?>">
                                         </div>
                                         <br>
                                         <form id="addnewcomment">
                                             <div class="form-group">
                                                 <textarea name="newcomment" id="newcomment" class="form-control" rows="3" placeholder="<?= $lang->trl('comment') ?> ..."></textarea>
                                             </div>
                                             <button type="button" data-id="<?= $company_data->company_id ?>" onclick="addcomment($(this).attr('data-id'))" class="btn btn-default float-right"><?= $lang->trl('Add comment') ?></button>
                                         </form>
                                     </div>
                                 </div>
                                 <!-- /.tab-pane -->
                             </div>
                             <!-- /.tab-content -->
                         </div><!-- /.card-body -->
                     </div>
                     <!-- /.card -->
                 </div>
                 <!-- /.col -->
             </div>

             <div class="row">

             </div>
         </div><!-- /.container-fluid -->
     </section>
     <?php if ($contact['rows'] > 0) : ?>
         <section class="content">
             <div class="container-fluid">
                 <div class="row">
                     <div class="col-12">
                         <div class="card">
                             <div class="card-header">
                                 <h3 class="card-title"><?= $lang->trl('Contact List') ?></h3>
                             </div>
                             <!-- /.card-header -->
                             <div class="card-body">
                                 <table id="example2" class="table table-bordered table-hover">
                                     <thead>
                                         <tr>
                                             <th><?= $lang->trl('Lastname') ?></th>
                                             <th><?= $lang->trl('Firstname') ?></th>
                                             <th><?= $lang->trl('Email') ?></th>
                                             <th><?= $lang->trl('Function') ?></th>
                                             <th><?= $lang->trl('Phone number') ?></th>
                                         </tr>
                                     </thead>
                                     <tbody>
                                         <?php foreach ($contact['data'] as $key => $infocontact) : ?>
                                            <tr>
                                                <td><?= ($infocontact->contact_firstname) ? $infocontact->contact_firstname : $lang->trl('No info') ?></td>
                                                <td><?= ($infocontact->contact_lastnamee) ? $infocontact->contact_lastnamee : $lang->trl('No info') ?></td>
                                                <td><?= ($infocontact->contact_email) ? $infocontact->contact_email : $lang->trl('No info') ?></td>
                                                <td><?= ($infocontact->title) ? $infocontact->title : $lang->trl('No info')  ?></td>
                                                <td><?= ($infocontact->phone_number) ? $infocontact->phone_number : $lang->trl('No info')  ?></td>
                                            </tr>
                                         <?php endforeach; ?>

                                     </tbody>
                                 </table>
                             </div>
                             <!-- /.card-body -->
                         </div>
                         <!-- /.card -->
                     </div>
                     <!-- /.col -->
                 </div>
                 <!-- /.row -->
             </div>
             <!-- /.container-fluid -->
         </section>
     <?php endif ?>
     <!-- /.content -->
 </div>

 <script>
     function laodcomment() {
         var company_id = $("#comment").attr("data-id");
         $.ajax({
             method: "POST",
             url: "/customer/comment",
             data: {
                 company_id: company_id
             },
             success: function(data) {
                 //console.log(data);
                 $("#comment").html(data);
             }
         })
     }
     window.onload = (event) => {
         laodcomment();
         //  console.log(comment);
     };



     function addcomment(company) {
         //console.log(company);
         var commentext = encodeURIComponent($("#newcomment").val());
         $.ajax({
             method: "POST",
             url: "/customer/newcomment",
             data: {
                 company_id: company,
                 comment: commentext
             },
             success: function(msg) {
                 //console.log(msg);
                 var val = msg.split("||");
                 if (val[0] == "true") {
                     $("#addnewcomment")[0].reset();
                     Toast.fire({
                         icon: 'success',
                         title: val[1]
                     });
                     laodcomment();
                 } else if (val[0] == "false") {
                     Toast.fire({
                         icon: 'error',
                         title: val[1]
                     });
                 }
             }
         })
     }
 </script>