<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1><?= $lang->trl('Edit contact') ?></h1>
                </div>
                <!-- <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">Ajouter un contact</li>
          </ol>
        </div> -->
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-8">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title"><?= $lang->trl('Edit contact') ?></h3>
                        </div>

                        <header class="text-center mb-4">
                            <div class="text-danger">
                                <h6 id="error_message"></h6>
                            </div>
                            <div class="text-success">
                                <h6 id="success_message"></h6>
                            </div>
                        </header>
                        <!-- /.card-header -->
                        <!-- form start -->

                        <form action="" method="POST">
                            <div class="card-body">
                                <input type="hidden" id="contact_id" value="<?= $contact->contact_id ?>">
                                <div class="form-group">
                                    <label for="first_name"><?= $lang->trl('First name') ?></label>
                                    <input type="text" name="first_name" class="form-control" id="first_name" value="<?= $contact->contact_firstname ?>" placeholder="">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1"><?= $lang->trl('Last name') ?></label>
                                    <input type="text" name="last_name" class="form-control" id="last_name" value="<?= $contact->contact_lastname ?>" placeholder="">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1"><?= $lang->trl('Phone number') ?></label>
                                    <input type="text" name="phone_number" class="form-control" id="phone_number" value="<?= $contact->phone_number ?>" placeholder="">
                                </div>
                                <div class="form-group">
                                    <label for="fonction"><?= $lang->trl('Title') ?></label>
                                    <input type="text" name="fonction" class="form-control" value="<?= $contact->title ?>" id="fonction" placeholder="">
                                </div>
                                <div class="form-group">
                                    <label for="company"><?= $lang->trl('Company') ?></label>
                                    <select name="company" id="company" class="form-control">
                                        <option value="<?= $contact->company_id ?>"><?= $contact->company ?></option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="email"><?= $lang->trl('Email') ?> </label>
                                    <input type="email" name="email" class="form-control" id="email" value="<?= $contact->contact_email ?>" placeholder="">
                                </div>
                                <!-- <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" name="password" class="form-control" id="password">
                  </div> -->
                                <!-- <div class="form-group">
                    <label >Select your avatar</label>
                    <div class="input-group">
                      <div class="custom-file">
                        <input type="file" name="avatar" class="custom-file-input" id="avatar">
                        <label class="custom-file-label" for="avatar">Choose file</label>
                      </div>
                      <div class="input-group-append">
                        <span class="input-group-text">Upload</span>
                      </div>
                    </div>
                  </div> -->
                                <!-- <div class="form-check">
                                    <input type="checkbox" name="is_active" class="form-check-input" id="is_active">
                                    <label class="form-check-label" for="is_active"><?= $lang->trl('Is active') ?></label>
                                </div>
                                <div class="form-check">
                                    <input type="checkbox" name="is_manager" class="form-check-input" id="is_manager">
                                    <label class="form-check-label" for="is_manager"><?= $lang->trl('Is manager') ?></label>
                                </div> -->
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="button" id="submit_contact" class="btn btn-primary pull-right"><?= $lang->trl('Update') ?></button>
                            </div>
                        </form>
                    </div>
                    <!-- /.card -->


                </div>

            </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->


<script>
    $('#submit_contact').click(function() {
        updateContact();
    })

    function updateContact() {
        document.getElementById('submit_contact').innerHTML = "<?= $lang->trl('Saving contact, please wait...') ?> <i class='fa fa-spinner fa-spin'></i>";

        
        var contact_id = encodeURIComponent($("#contact_id").val());
        var first_name = encodeURIComponent($("#first_name").val());
        var last_name = encodeURIComponent($("#last_name").val());
        var phone_number = encodeURIComponent($("#phone_number").val());
        var fonction = encodeURIComponent($("#fonction").val());
        var company = encodeURIComponent($("#company").val());
        var email = encodeURIComponent($("#email").val());


        // alert(code_naf)
        $.ajax({
            url: '/customer/updatecontact/',
            type: 'POST',
            data: {
                contact_id : contact_id,
                first_name: first_name,
                last_name: last_name,
                phone_number: phone_number,
                fonction: fonction,
                company: company,
                email: email
            },

            success: function(msg) {
                var val = msg.split('||');
                console.log(msg);
                if (val[0] == "false") {
                    $("#error_message").html(val[1]);
                    $("#error_message").show();
                    $("#submit_contact").attr("disabled", false);
                    $("#submit_contact").html("Enregistrer");

                } else if (val[0] == "true") {
                    $("#success_message").html(val[1]);
                    $("#error_message").html("");
                    $("#success_message").show();
                    $("#submit_contact").html(val[1]).attr("disabled", true);

                    rnd = Math.random();
                    window.location.href = '/customer/contacts/' + rnd;


                }

            },
            error: function(resultat, statut, erreur) {
                $("#error_message").html("<?= $lang->trl('Error, please try again') ?>. <i class='fa fa-stop-circle'></i>");
                console.log('Resultat : ' + resultat);
                console.log('Statut : ' + statut);
                console.log('Erreur : ' + erreur);
            }
        });

    }
</script>