<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1><?= $lang->trl('Contact') ?> <span><a type="button" href="/customer/contact_new" class="btn btn-primary"><?= $lang->trl('Add Contact') ?></a></span></h1>

        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="/customer/dashboard"><?= $lang->trl('Home') ?></a></li>
            <li class="breadcrumb-item active"><?= $lang->trl('Contact') ?></li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title"><?= $lang->trl('Contact List') ?></h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <table id="example2" class="table table-bordered table-hover">
                <thead>
                  <tr>
                    <th><?= $lang->trl('Last name') ?></th>
                    <th><?= $lang->trl('First name') ?></th>
                    <th><?= $lang->trl('Fonction') ?></th>
                    <th><?= $lang->trl('Company') ?></th>
                    <th><?= $lang->trl('Action') ?></th>
                  </tr>
                </thead>
                <tbody>
                  <?php foreach ($contacts as $contact) : ?>
                    <tr>
                      <td><?= $contact->contact_firstname ?></td>
                      <td><?= $contact->contact_lastname ?></td>
                      <td><?= $contact->title ?></td>
                      <td><?= $contact->company ?></td>
                      <td> <a class="btn btn-default btn-xs" data-id="<?= $contact->contact_id ?>" onclick="viewContact($(this).attr('data-id'))" title="<?= $lang->trl('View') ?>"><i class="fas fa-eye"></i></a> <a href="/editcontact_<?= $contact->contact_id ?>" class="btn btn-default btn-xs" data-id="<?= $contact->contact_id ?>" title="<?= $lang->trl('Edit') ?>"><i class="fas fa-edit"></i></a><a href="/customer/contact/<?= $contact->contact_id ?>" class="btn btn-primary btn-xs" title="<?= $lang->trl('Open') ?>" data-id="" onclick=""><i class="fas fa-folder"></i></a>
                        <?php if ($contact->is_active == 0) { ?>
                          <a class="btn btn-danger btn-xs" data-id="<?= $contact->contact_id ?>" title="<?= $lang->trl('Activate') ?>" onclick="enableContact($(this).attr('data-id'))">
                            <i class="fas fa-times-circle">
                            </i>
                          </a>
                        <?php } elseif ($contact->is_active == 1) { ?>
                          <a class="btn btn-success btn-xs" data-id="<?= $contact->contact_id ?>" title="<?= $lang->trl('Desactivate') ?>" onclick="desableContact($(this).attr('data-id'))">
                            <i class="fas fa-check">
                            </i>
                          </a>
                        <?php } ?>
                      </td>
                    </tr>
                  <?php endforeach; ?>
                </tbody>
              </table>
              <!-- </div> -->
              <!-- /.card-body -->
              <!-- </div> -->
              <!-- /.card -->
            </div>
            <!-- /.col -->
          </div>
          <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
  </section>
  <!-- /.content -->
</div>
<!-- /.content-wrapper -->



<div class="modal fade" id="contactinfo">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title"><?= $lang->trl('Contact info') ?></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="contactview">
      </div>
      <div class="modal-footer justify-content-between">
        <button type="button" class="btn btn-default" data-dismiss="modal"><?= $lang->trl('Close') ?></button>
        <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<script>
  function viewContact(contact_id) {
    // console.log(contact_id)
    $.ajax({
      type: "POST",
      url: "/customer/viewcontinfo",
      data: {
        contact_id: contact_id
      },
      success: function(data) {
        // console.log(data)
        $("#contactview").html(data);
        $("#contactinfo").modal('show');
      }
    })
  }

  function enableContact(contact) {
    // alert(contact)
    $.ajax({
      method: "POST",
      url: "/customer/enablecontact",
      data: {
        contact: contact
      },
      success: function(data) {
        console.log(data);
        var val = data.split("||");
        if (val[0] == "true") {
          location.reload();
        } else if (val[0] == "false") {
          taostr.error(val[1]);
        }
      }
    })
  }

  function desableContact(contact) {
    // alert(contact)
    $.ajax({
      method: "POST",
      url: "/customer/desablecontact",
      data: {
        contact: contact
      },
      success: function(data) {
        console.log(data);
        var val = data.split("||");
        if (val[0] == "true") {
          location.reload();
        } else if (val[0] == "false") {
          taostr.error(val[1]);
        }
      }
    })
  }
</script>