<div class="middle-header">
    <div class="container-fluid">
        <div class="row align-items-center">
            <div class="col-xl-4 col-lg-12 col-md-12 col-sm-12">
                <div class="logo">
                    <a href="index-2.html">
                        <img src="<?= $iniObj->UIPath ?>/img/logo2.png" alt="image">
                    </a>
                </div>
            </div>
            <div class="col-xl-4 col-lg-6 col-md-6 col-sm-8">
                <form>
                    <input type="text" class="input-search" placeholder="Search...">
                    <button type="submit"><i class='bx bx-search-alt'></i></button>
                </form>
            </div>
            <div class="col-xl-4 col-lg-6 col-md-6 col-sm-4">
                <div class="others-option d-flex align-items-center justify-content-end">
                    <div class="option-item">
                        <div class="wishlist-btn">
                            <a href="wishlist.html"><i class='bx bx-heart'></i></a>
                        </div>
                    </div>
                    <div class="option-item">
                        <div class="cart-btn">
                            <a href="#" data-toggle="modal" data-target="#shoppingCartModal"><i class='bx bx-cart'></i><span>3</span></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="navbar-area navbar-style-two">
    <div class="theme-responsive-nav">
        <div class="container">
            <div class="theme-responsive-menu">
                <div class="logo">
                    <a href="index-2.html">
                        <img src="<?= $iniObj->UIPath ?>/img/logo.png" alt="logo">
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="theme-nav">
        <div class="container-fluid">
            <nav class="navbar navbar-expand-md navbar-light">
                <div class="megamenu-container">
                    <div class="megamenu-title">
                        <i class='bx bx-category'></i> Catégories
                    </div>
                    <div class="megamenu-category">
                        <ul class="nav">
                            <li class="nav-item">
                                <a href="#" class="nav-link">Accessories <i class="flaticon-next"></i></a>
                                <ul class="dropdown-menu megamenu">
                                    <li class="row align-items-center">
                                        <div class="col-lg-4 col-sm-6">
                                            <h3>Accessories I</h3>
                                            <ul class="megamenu-nav">
                                                <li><a href="shop.html">EKG/ECG Machines</a></li>
                                                <li><a href="shop.html">Surgical Tables</a></li>
                                                <li><a href="shop.html">Blanket Warmers</a></li>
                                                <li><a href="shop.html">Electrosurgical Units</a></li>
                                                <li><a href="shop.html">Surgical Lights</a></li>
                                            </ul>
                                        </div>
                                        <div class="col-lg-4 col-sm-6">
                                            <h3>Accessories II</h3>
                                            <ul class="megamenu-nav">
                                                <li><a href="shop.html">Stretchers</a></li>
                                                <li><a href="shop.html">Defibrillators</a></li>
                                                <li><a href="shop.html">Anesthesia Machines</a></li>
                                                <li><a href="shop.html">Patient Monitors</a></li>
                                                <li><a href="shop.html">Sterilizers</a></li>
                                            </ul>
                                        </div>
                                        <div class="col-lg-4 col-sm-6">
                                            <div class="custom-media">
                                                <a href="products-details.html" class="d-block"><img src="<?= $iniObj->UIPath ?>/img/menu-img1.jpg" alt="image"></a>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link">Pharmacy <i class="flaticon-next"></i></a>
                                <ul class="dropdown-menu megamenu">
                                    <li class="row align-items-center">
                                        <div class="col-lg-4 col-sm-6">
                                            <h3>Pharmacy 01</h3>
                                            <ul class="megamenu-nav">
                                                <li><a href="shop.html">Acetaminophen</a></li>
                                                <li><a href="shop.html">Adderall</a></li>
                                                <li><a href="shop.html">Amitriptyline</a></li>
                                                <li><a href="shop.html">Amlodipine</a></li>
                                                <li><a href="shop.html">Amoxicillin</a></li>
                                            </ul>
                                        </div>
                                        <div class="col-lg-4 col-sm-6">
                                            <h3>Pharmacy 02</h3>
                                            <ul class="megamenu-nav">
                                                <li><a href="shop.html">Cephalexin</a></li>
                                                <li><a href="shop.html">Ciprofloxacin</a></li>
                                                <li><a href="shop.html">Citalopram</a></li>
                                                <li><a href="shop.html">Clindamycin</a></li>
                                                <li><a href="shop.html">Clonazepam</a></li>
                                            </ul>
                                        </div>
                                        <div class="col-lg-4 col-sm-6">
                                            <h3>Pharmacy 03</h3>
                                            <ul class="megamenu-nav">
                                                <li><a href="shop.html">Ativan</a></li>
                                                <li><a href="shop.html">Atorvastatin</a></li>
                                                <li><a href="shop.html">Azithromycin</a></li>
                                                <li><a href="shop.html">Benzonatate</a></li>
                                                <li><a href="shop.html">Brilinta</a></li>
                                            </ul>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link">Health & Nutrition <i class="flaticon-next"></i></a>
                                <ul class="dropdown-menu megamenu">
                                    <li class="row align-items-center">
                                        <div class="col-lg-4 col-sm-6">
                                            <h3>Health Drinks</h3>
                                            <ul class="megamenu-nav">
                                                <li><a href="shop.html">Children</a></li>
                                                <li><a href="shop.html">Diabetic Drinks</a></li>
                                                <li><a href="shop.html">Glucose Powder</a></li>
                                                <li><a href="shop.html">Men & Women</a></li>
                                            </ul>
                                        </div>
                                        <div class="col-lg-4 col-sm-6">
                                            <h3>Breakfast Cereals</h3>
                                            <ul class="megamenu-nav">
                                                <li><a href="shop.html">Cereal Basics</a></li>
                                                <li><a href="shop.html">Sugar & Carbs</a></li>
                                                <li><a href="shop.html">Misleading Claims</a></li>
                                                <li><a href="shop.html">Better Breakfasts</a></li>
                                            </ul>
                                        </div>
                                        <div class="col-lg-4 col-sm-6">
                                            <h3>Management</h3>
                                            <ul class="megamenu-nav"> 
                                                <li><a href="shop.html">Ativan</a></li>
                                                <li><a href="shop.html">Azithromycin</a></li>
                                                <li><a href="shop.html">Benzonatate</a></li>
                                                <li><a href="shop.html">Brilinta</a></li>
                                            </ul>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link">Personal Equipment <i class="flaticon-next"></i></a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item"><a href="shop.html" class="nav-link">Cosmetic</a></li>
                                    <li class="nav-item"><a href="shop.html" class="nav-link">Microscope</a></li>
                                    <li class="nav-item"><a href="shop.html" class="nav-link">Hearing Aid</a></li>
                                    <li class="nav-item"><a href="shop.html" class="nav-link">Metal Stethoscope</a></li>
                                    <li class="nav-item"><a href="shop.html" class="nav-link">Medical Glass</a></li>
                                    <li class="nav-item"><a href="shop.html" class="nav-link">Isometric</a></li>
                                    <li class="nav-item"><a href="shop.html" class="nav-link">Mask</a></li>
                                    <li class="nav-item"><a href="shop.html" class="nav-link">Blood Pressure</a></li>
                                    <li class="nav-item"><a href="shop.html" class="nav-link">Face Mask</a></li>
                                    <li class="nav-item"><a href="shop.html" class="nav-link">Gloves</a></li>
                                    <li class="nav-item"><a href="shop.html" class="nav-link">Sanitizer</a></li>
                                </ul>
                            </li>
                            <li class="nav-item"><a href="shop.html" class="nav-link">Diagnostic Sets</a></li>
                            <li class="nav-item"><a href="shop.html" class="nav-link">Microscope</a></li>
                            <li class="nav-item"><a href="shop.html" class="nav-link">Needle & Syringes</a></li>
                            <li class="nav-item"><a href="shop.html" class="nav-link">OT Therapy</a></li>
                            <li class="nav-item"><a href="shop.html" class="nav-link">First Aid</a></li>
                            <li class="nav-item"><a href="shop.html" class="nav-link">Transport</a></li>
                        </ul>
                    </div>
                </div>
                <div class="collapse navbar-collapse mean-menu">
                    <ul class="navbar-nav">
                        <li class="nav-item"><a href="javascript:void(0)" class="nav-link">Strudture Chimique</a></li>
                        <li class="nav-item"><a href="javascript:void(0)" class="nav-link">Demande de Certificats</a></li>
                        <li class="nav-item"><a href="javascript:void(0)" class="nav-link">Fiche de sécurité</a></li>
                        <li class="nav-item"><a href="javascript:void(0)" class="nav-link">Suivi de commande</a></li>
                        <li class="nav-item"><a href="javascript:void(0)" class="nav-link">Offres</a></li>
                    </ul>
                </div>
            </nav>
        </div>
    </div>
</div>
