<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1><?= $lang->trl('Add a mission') ?></h1>
        </div>
        <!-- <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">Ajouter une mission</li>
          </ol>
        </div> -->
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <!-- left column -->
        <div class="col-md-8">
          <!-- general form elements -->
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title"><?= $lang->trl('Add a mission') ?></h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form>
              <div class="card-body">
                <!-- <div class="form-group">
                  <label for="exampleInputEmail1">Mission label</label>
                  <input type="text" class="form-control" name="" id="mission_label" placeholder="Mission label">
                </div> -->
                <div class="form-group">
                  <label for="mission_label"><?= $lang->trl('Mission type') ?></label>
                  <select id="mission_label" name="mission_label" class="form-control">
                    <option value=""><?= $lang->trl('Select a mission type') ?></option>
                    <?php foreach ($action_types as $key => $type) : ?>
                      <option value="<?= $type->action_type_id ?>"><?= $type->action_type_label ?></option>
                    <?php endforeach; ?>
                  </select>
                </div>
                <div class="form-group">
                  <label><?= $lang->trl('Mission Date') ?>:</label>
                  <div class="input-group date" id="reservationdate" data-target-input="nearest">
                    <input type="text" id="mission_date" name="mission_date" placeholder="Ex: <?= date('Y/m/d') ?>" class="form-control datetimepicker-input" data-target="#reservationdate" />
                    <div class="input-group-append" data-target="#reservationdate" data-toggle="datetimepicker">
                      <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                    </div>
                  </div>
                </div>
                <div class="form-group">
                  <label for="mission_compagny"><?= $lang->trl('Select a company') ?></label>
                  <select id="mission_compagny" name="mission_compagny" class="form-control" onchange="laodContact($(this).find(':selected').attr('data-id'))">
                    <option value=""><?= $lang->trl('Select a company') ?></option>
                    <?php foreach ($companies as $key => $compagny) : ?>
                      <option data-id="<?= $compagny->company_id ?>" value="<?= $compagny->company_id ?>"><?= $compagny->company_name ?></option>
                    <?php endforeach; ?>
                  </select>
                </div>
                <div class="form-group">
                  <label for="mission_contact"><?= $lang->trl('Select a contact') ?></label>
                  <select id="mission_contact" name="mission_contact" class="form-control">

                  </select>
                </div>

              </div>
              <!-- /.card-body -->

              <div class="card-footer">
                <button type="button" onclick="newMission()" id="submit_mission" class="btn btn-primary"><?= $lang->trl('Submit') ?></button>
              </div>
            </form>
          </div>
          <!-- /.card -->


        </div>
        <!--/.col (left) -->
        <!-- right column -->
        <!-- <div class="col-md-6"> -->
        <!-- Form Element sizes -->
        <!-- <div class="card card-success">
              <div class="card-header">
                <h3 class="card-title">Different Height</h3>
              </div>
              <div class="card-body">
                <input class="form-control form-control-lg" type="text" placeholder=".form-control-lg">
                <br>
                <input class="form-control" type="text" placeholder="Default input">
                <br>
                <input class="form-control form-control-sm" type="text" placeholder=".form-control-sm">
              </div> -->
        <!-- /.card-body -->
        <!-- </div> -->
        <!-- /.card -->


        <!-- /.card -->
        <!-- </div> -->
        <!--/.col (right) -->
      </div>
      <!-- /.row -->
    </div><!-- /.container-fluid -->
  </section>
  <!-- /.content -->
</div>
<!-- /.content-wrapper -->

<script>
  $(function() {
    //Date picker
    $('#reservationdate').datetimepicker({
      format : 'L'
    });
  })

  function newMission() {
    $("#submit_mission").attr("disabled", true);
    document.getElementById('submit_mission').innerHTML = "<?= $lang->trl('Saving') ?>... Veuillez patienter  ... <i class='fa fa-spinner fa-spin'></i>";
    var mission_label = ($("#mission_label").val());
    var mission_date = $("#mission_date").val();
    var mission_contact = encodeURI($("#mission_contact").val());
    var mission_compagny = encodeURI($("#mission_compagny").val());
    // var current_date = Date().toString();
    // console.log(mission_date);

    //toastr.warning('Lorem ipsum dolor sit amet, consetetur sadipscing elitr.');
    $.ajax({
      method: "POST",
      url: "/customer/newmission",
      data: {
        mission_compagny: mission_compagny,
        mission_label: mission_label,
        mission_date: mission_date,
        mission_contact: mission_contact
      },
      success: function(msg) {
        console.log(msg);
        var val = msg.split("||");
        if (val[0] == "true") {
          Toast.fire({
            icon: 'success',
            title: val[1]
          });
          $("#submit_mission").attr("disabled", false);
          $("#submit_mission").html("<?= $lang->trl('Submit') ?>");
          window.location.href = '/customer/mission_list/';
        } else if (val[0] == "false") {
          $("#submit_mission").attr("disabled", false);
          $("#submit_mission").html("<?= $lang->trl('Submit') ?>");
          toastr.error(val[1]);
        }
      }
    })
  }


  function laodContact(id) {
    //console.log(id);
    $.ajax({
      method: "POST",
      url: "/customer/getcontact",
      data: {
        id: id
      },
      success: function(data) {
        //console.log(data);
        $("#mission_contact").html(data);
      }
    })
  }
</script>