<?php
if ($iniObj->debugViews)
    echo __FILE__;
$title = "Créer un produit";
include _VIEW_PATH . '/dashboard_head.phtml';
include _VIEW_PATH . $lib->lang . '/dashboard_header.phtml';
include _VIEW_PATH . $lib->lang . '/dashboard_sidebar.phtml';
?>

<!-- ============================================================== -->
<!-- Start right Content here -->
<!-- ============================================================== -->
<div class="main-content">

    <div class="page-content">
        <div class="container-fluid">

            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box d-flex align-items-center justify-content-between">
                        <h4 class="mb-0 font-size-18">Créer un article </h4>


                    </div>
                </div>
            </div>
            <!-- end page title -->

        </div> <!-- container-fluid -->
    </div>
    <!-- End Page-content -->

    <?php
    include _VIEW_PATH . $lib->lang . '/dashboard_footer.phtml';
    include _VIEW_PATH . 'dashboard_include_files.phtml';
    ?>


