<?php
// if($iniObj->debugViews) echo __FILE__ ;
// $carouselActive = true;
// $title = "Articles neufs et occasions - Professionnel - Dépôt vente - Electroménager - Décoration - Informatique - Jeux vidéo - Son - Image - Téléphonie - Bricolage - Jardinage - Animalerie";
include _VIEW_PATH . "/common_header.phtml"; ?>

<?php
include _VIEW_PATH . "/customer/profile_left_menu.phtml";
include _VIEW_PATH . "common_top_bar.phtml";
// include _VIEW_PATH.$lib->lang."/top_menu.phtml";
?>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1><?= $title ?> </h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/customer/dashboard"><?= $lang->trl('Home') ?></a></li>
                        <li class="breadcrumb-item active"><?= $title ?></li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-8">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title"><?= $lang->trl('Prospector') ?></h3>
                        </div>

                        <header class="text-center mb-4">
                            <div class="text-danger">
                                <h6 id="error_message"></h6>
                            </div>
                            <div class="text-success">
                                <h6 id="success_message"></h6>
                            </div>
                        </header>
                        <!-- /.card-header -->
                        <!-- form start -->

                        <form id="user-form" action="" method="POST">
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="first_name"><?= $lang->trl('First name') ?></label>
                                    <input type="text" name="first_name" class="form-control" id="firstname" placeholder="John" onkeypress="return (event.charCode > 64 && event.charCode < 91) || (event.charCode > 96 && event.charCode < 123) || (event.charCode==32)">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1"><?= $lang->trl('Last name') ?></label>
                                    <input type="text" name="last_name" class="form-control" id="lastname" placeholder="DOE" onkeypress="return (event.charCode > 64 && event.charCode < 91) || (event.charCode > 96 && event.charCode < 123) || (event.charCode==32)">
                                </div>
                                <div class="form-group">
                                    <label for="company"><?= $lang->trl('Role') ?></label>
                                    <select name="company" id="role" class="form-control" onchange="verifyrole($(this).find(':selected').attr('data-id'))">
                                        <option value=""><?= $lang->trl('Select a Role') ?></option>
                                        <?php foreach ($roles as $key => $role) : ?>
                                            <option data-id="<?= $role->role_id ?>" value="<?= $role->role_id ?>"><?= ucfirst($role->role_label) ?></option>
                                        <?php endforeach ?>
                                    </select>
                                </div>
                                <div class="form-group" id="manager-div">
                                    <label for="company"><?= $lang->trl('Manager') ?></label>
                                    <select name="company" id="manager" class="form-control">
                                        <option value=""><?= $lang->trl('Select a Manager') ?></option>
                                        <?php foreach ($managers as $key => $manager) : ?>
                                            <option value="<?= $manager->user_id ?>"><?= ucfirst($manager->firstname) . ' ' . ucfirst($manager->lastname) ?></option>
                                        <?php endforeach ?>
                                    </select>
                                </div>

                                <div class="form-group">
                                    <label for="email"><?= $lang->trl('Email address') ?></label>
                                    <input type="email" name="email" class="form-control" id="email" placeholder="<?= $lang->trl('Email address') ?>">
                                </div>
                                <!-- <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" name="password" class="form-control" id="password">
                  </div> -->
                                <!-- <div class="form-group">
                    <label >Select your avatar</label>
                    <div class="input-group">
                      <div class="custom-file">
                        <input type="file" name="avatar" class="custom-file-input" id="avatar">
                        <label class="custom-file-label" for="avatar">Choose file</label>
                      </div>
                      <div class="input-group-append">
                        <span class="input-group-text">Upload</span>
                      </div>
                    </div>
                  </div> -->
                                <div class="form-check">
                                    <input type="checkbox" name="is_active" class="form-check-input" id="is_active" value="on">
                                    <label class="form-check-label" for="is_active"><?= $lang->trl('Active') ?></label>
                                </div>
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="button" id="usersubmit" onclick="saveprop()" class="btn btn-primary pull-right"><?= $lang->trl('Submit') ?></button>
                            </div>
                        </form>
                    </div>
                    <!-- /.card -->


                </div>

            </div><!-- /.container-fluid -->

    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->


<?php include _VIEW_PATH . $lib->lang . "/common_footer.phtml"; ?>
<?php include _VIEW_PATH . "/common_include_files.phtml"; ?>
<script>
    function saveprop() {
        document.getElementById('usersubmit').innerHTML = "<?= $lang->trl('Submitting') ?>  ... <i class='fa fa-spinner fa-spin'></i>";
        document.getElementById('usersubmit').disabled = true;
        var active = $("#is_active:checked").val();
        var firstname = encodeURI($("#firstname").val());
        var lastname = encodeURI($("#lastname").val());
        var manager = $("#manager").val();
        var email = encodeURI($("#email").val());
        var role = $("#role").val();
        // console.log(active, firstname, lastname, manager, email)
        $.ajax({
            method: "POST",
            url: "/customer/addprosp",
            data: {
                active: active,
                firstname: firstname,
                lastname: lastname,
                manager: manager,
                email: email,
                role: role
            },
            success: function(msg) {
                // console.log(msg)
                var val = msg.split('||');
                if (val[0] == "false") {
                    toastr.error(val[1]);
                    document.getElementById('usersubmit').disabled = false;
                    document.getElementById('usersubmit').innerHTML = "<?= $lang->trl('Submit') ?>";
                } else if (val[0] == "true") {
                    toastr.success(val[1]);
                    document.getElementById('usersubmit').disabled = false;
                    document.getElementById('usersubmit').innerHTML = "<?= $lang->trl('Submit') ?>";
                    $("#user-form")[0].reset();
                    window.location.href = '/customer/prospectors/';
                }
            }
        })
    }

    function verifyrole(id) {
        if (id == 1) {
            document.getElementById('manager-div').style.display = 'none';
        } else {
            document.getElementById('manager-div').style.display = 'block';
        }
    }
</script>