<?php
// if($iniObj->debugViews) echo __FILE__ ;
// $carouselActive = true;
// $title = "Articles neufs et occasions - Professionnel - Dépôt vente - Electroménager - Décoration - Informatique - Jeux vidéo - Son - Image - Téléphonie - Bricolage - Jardinage - Animalerie";
include _VIEW_PATH . "/common_header.phtml"; ?>

<?php
include _VIEW_PATH . "/customer/profile_left_menu.phtml";
include _VIEW_PATH . "common_top_bar.phtml";
// include _VIEW_PATH.$lib->lang."/top_menu.phtml";
?>



<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Contact</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-3">

                    <!-- Profile Image -->
                    <div class="card card-primary card-outline">
                        <div class="card-body box-profile">
                            <div class="text-center">
                                <img class="profile-user-img img-fluid img-circle" src="<?= $iniObj->UIPath ?>/img/user_placeholder.png" alt="User profile picture">
                            </div>

                            <h3 class="profile-username text-center"><?= ucfirst($contactdata->contact_firstname) . ' ' . ucfirst($contactdata->contact_lastname) ?></h3>

                            <p class="text-muted text-center"><?= $contactdata->title ?></p>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->

                    <!-- About Me Box -->
                    <div class="card card-primary">
                        <!-- /.card-header -->
                        <div class="card-body">
                            <strong><i class="fas fa-book mr-1"></i> <?= $lang->trl('Company') ?></strong>

                            <p class="text-muted">
                                <?= $contactdata->company ?>
                            </p>

                            <hr>

                            <strong><i class="fas fa-envelope mr-1"></i> <?= $lang->trl('Email') ?></strong>

                            <p class="text-muted"><?= $contactdata->contact_email ?></p>

                            <hr>

                            <strong><i class="fas fa-phone mr-1"></i> <?= $lang->trl('Phone number') ?></strong>

                            <p class="text-muted"><?= $contactdata->phone_number ?> </p>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
                <div class="col-md-9">
                    <div class="card">
                        <div class="card-header p-2">
                            <ul class="nav nav-pills">
                                <li class="nav-item"><?= $lang->trl('Timeline') ?></li>
                            </ul>
                        </div><!-- /.card-header -->
                        <div class="card-body">
                            <div class="tab-content">
                                <div class="active tab-pane" id="timeline">
                                    <!-- The timeline -->


                                    <div class="timeline timeline-inverse">
                                        <!-- timeline time label -->
                                        <?php if ($contacttimeline) { ?>
                                            <?php foreach ($contacttimeline as $key => $timeline) : ?>
                                                <div class="time-label">
                                                    <span class="bg-danger">
                                                        <?= date('d/m/Y', strtotime($timeline->mission_date)) ?>
                                                    </span>
                                                </div>
                                                <!-- /.timeline-label -->
                                                <!-- timeline item -->
                                                <div>
                                                    <?php
                                                    if ($timeline->mission_label == 1) {
                                                        echo '<i class="fas fa-comments bg-warning"></i>';
                                                    } else if ($timeline->mission_label == 2) {
                                                        echo '<i class="fas fa-envelope bg-primary"></i>';
                                                    } else if ($timeline->mission_label == 3) {
                                                        echo '<i class="fas fa-user bg-info"></i>';
                                                    } else if ($timeline->mission_label == 4) {
                                                        echo '<i class="fas fa-phone bg-purple"></i>';
                                                    }

                                                    ?>

                                                    <div class="timeline-item">
                                                        <!-- <span class="time"><i class="far fa-clock"></i> 5 mins ago</span> -->

                                                        <h3 class="timeline-header border-0"><a href="#"><?= ucfirst($timeline->user_firstname) . ' ' . ucfirst($timeline->user_lastname) ?> </a> <?= $timeline->action ?>
                                                        </h3>
                                                    </div>
                                                </div>
                                                <!-- END timeline item -->
                                            <?php endforeach; ?>
                                        <?php } else { ?>
                                            <div class="alert alert-warning alert-dismissible">
                                                
                                                <?= $lang->trl('No timelines') ?>
                                            </div>
                                        <?php } ?>
                                    </div>

                                </div>
                                <!-- /.tab-pane -->
                            </div>
                            <!-- /.tab-content -->
                        </div><!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>



<?php include _VIEW_PATH . $lib->lang . "/common_footer.phtml"; ?>
<?php include _VIEW_PATH . "/common_include_files.phtml"; ?>