
<?php
if ($iniObj->debugViews)
    echo __FILE__;
$title = "Type d'Utilisateurs || Tableau de bord || ".$iniObj->serviceName;
include _VIEW_PATH . '/dashboard_head.phtml';
include _VIEW_PATH . $lib->lang . '/dashboard_header.phtml';
include _VIEW_PATH . $lib->lang . '/dashboard_sidebar.phtml';
?>

<!-- ============================================================== -->
<!-- Start right Content here -->
<!-- ============================================================== -->
<div class="main-content">

    <div class="page-content">
        <div class="container-fluid">

            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box d-flex align-items-center justify-content-between">
                        <h4 class="mb-0 font-size-18">Types d'Utilisateur
                            <small>
                                <!-- Button trigger modal -->
                                <button type="button" class="btn btn-primary waves-effect waves-light" data-toggle="modal" data-target="#adduserrole">
                                    Ajouter un role
                                </button>
                            </small>
                        </h4>
                    </div>
                </div>
            </div>
            <!-- end page title -->

            <!-- Modal -->
            <div class="modal fade" id="adduserrole" tabindex="-1" role="dialog" aria-labelledby="adduserrole" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Créer un Utilisateur</h5>
                            <button type="button" class="close waves-effect waves-light" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="form-group">
                                <label for="lastname">Rôle</label>
                                <input type="text" id="lastname" name="lastname" class="form-control" placeholder="Nom">
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary waves-effect waves-light" data-dismiss="modal">Fermer</button>
                            <button type="button" class="btn btn-primary waves-effect waves-light">Créer</button>
                        </div>
                    </div>
                </div>
            </div>



            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Touts les utilisateurs</h4>
                            <p class="card-subtitle mb-4">
                            </p>

                            <table id="state-saving-datatable" class="table activate-select dt-responsive nowrap">
                                <thead>
                                    <tr>
                                        <th>Rôles</th>
                                        <th>Utilisateurs</th>
                                        <th>Statut</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>

                                <tbody>
                                    <tr>
                                        <td>Tiger Nixon</td>
                                        <td>System Architect</td>
                                        <td>Edinburgh</td>
                                        <td>61</td>
                                    </tr>
                                    
                                </tbody>
                            </table>

                        </div> <!-- end card body-->
                    </div> <!-- end card -->
                </div><!-- end col-->
            </div>
            <!-- end row-->

        </div> <!-- container-fluid -->
    </div>
    <!-- End Page-content -->

    <?php
    include _VIEW_PATH . $lib->lang . '/dashboard_footer.phtml';
    include _VIEW_PATH . 'dashboard_include_files.phtml';
    ?>

